### ISSUE TITLE
In Browser StageMonitor Icon doesnt show up

### ISSUE THREAD

**Issue by rathna82** [stagemonitor/stagemonitor#121]
New to Stagemonitor, planning to use for our organization.
I did all the steps mentioned in the startup guide but cant see the icon at the bottom. 
Placed all required jars into Web-INF/lib
Created stage monitor props file in web-inf/classes
restarted app.

Environment
Apache Tomcat 8
Servlet 3.0
Ant build
XSL front end (no JSP does that matter??)

Can some one please help me?

**Comment by felixbarny** [comment]
Anything in the logs? Which jars did you add?

**Comment by rathna82** [comment]
I dropped the jars in different folders and this is how it behaved. In both cases the stage monitor icon didn't show up

Scenario:1
I dropped the stagemonitor-web-0.19.2.jar  and all other dependant jars in my web-inf/lib (all jars built from gradle script) . Also put the stagemonitor.properties in web-inf/classes folder.
No error in logs (just Info as below).. My app is deployed succesfully and it works good but still the stagemonitor link is not in the web page.

03-Jan-2016 15:45:04.124 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive /opt/entrust/identityguard110/services/auth/IdentityGuardAuthService.war
03-Jan-2016 15:45:05.464 INFO [localhost-startStop-1] org.stagemonitor.core.instrument.AgentLoader$1.run Located valid 'tools.jar' at /opt/entrust/jdk1.8.0_66/jre/../lib/tools.jar
03-Jan-2016 15:45:05.812 INFO [localhost-startStop-1] org.stagemonitor.core.instrument.AgentLoader.loadAgent Trying to load agent @ /opt/entrust/apache-tomcat-8.0.28/lib/stagemonitor-javaagent-0.19.2.jar

Scenario:2 
I dropped the stagemonitor-web-0.19.2.jar  in web-inf/lib and all other jars in my apache-tomcat/lib (all jars built from gradle script) . stagemonitor.properties in web-inf/classes folder.

Here is the log on deployment of war...

03-Jan-2016 15:10:31.878 SEVERE [localhost-startStop-1] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChild: start: 
 org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[adminservice].StandardHost[localhost].StandardContext[/IdentityGuardAdminService]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:945)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1798)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.stagemonitor.web.monitor.filter.HttpRequestMonitorFilter.<init>(HttpRequestMonitorFilter.java:54)
	at org.stagemonitor.web.monitor.filter.HttpRequestMonitorFilter.<init>(HttpRequestMonitorFilter.java:50)
	at org.stagemonitor.web.WebPlugin.onStartup(WebPlugin.java:380)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5170)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 10 more

03-Jan-2016 15:10:31.880 SEVERE [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Error deploying web application archive e.war
 java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[adminservice].StandardHost[localhost].StandardContext[....]]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:729)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:945)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1798)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

List of Jars added:
![image](https://cloud.githubusercontent.com/assets/16502814/12080727/3d6bb71a-b232-11e5-8ffc-2783f1f7302c.png)

**Comment by rathna82** [comment]
This is a non-maven project.. I saw some threads relating to it which says stage monitor isnt working for non-maven... .. s there a working sample for non-maven?

**Comment by felixbarny** [comment]
Could you post what is being logged in scenario 1 on the first request? In that phase stagemonitor initializes. Also try to enable debug logging for `org.stagemonitor`. Also, do you have a proper slf4j binding in your classpath?

I don't have an example for non maven project but it should work. Maven is just a build tool a war that is built without maven is indistinguishable from one built with maven.

**Comment by rathna82** [comment]
Sorry about the huge file..just didnt want to miss anything

[debug_log.zip](https://github.com/stagemonitor/stagemonitor/files/77421/debug_log.zip)

**Comment by felixbarny** [comment]
It seems like your browser isn't requesting a HTML document. 

```
[2016-01-04 11:14:32,761] [http-nio-8444-exec-7] [DEBUG] [com.....adminservices.webapp.ControllerServlet] ------------  PROCESS NEW REQUEST  ------------
[2016-01-04 11:14:32,812] [http-nio-8444-exec-7] [DEBUG] [com.....adminservices.webapp.ControllerServlet] Using module: default
[2016-01-04 11:14:32,812] [http-nio-8444-exec-7] [DEBUG] [com.....adminservices.webapp.ControllerServlet] Do: Start.null
[2016-01-04 11:14:32,812] [http-nio-8444-exec-7] [DEBUG] [com.....adminservices.webapp.ControllerServlet] Requested locale: en_US
[2016-01-04 11:14:32,815] [http-nio-8444-exec-7] [DEBUG] [com.....adminservices.webapp.ControllerServlet] Request for Start/start of type POST requires csrfToken: false
[2016-01-04 11:14:32,820] [http-nio-8444-exec-7] [DEBUG] [com.....adminservices.webapp.ControllerServlet] Received authorization: com.........webadmin.IgAdminAuthContext$Authorized@439a050f
[2016-01-04 11:14:32,820] [http-nio-8444-exec-7] [DEBUG] [com.....adminservices.webapp.ControllerServlet] Action: com.........webadmin.SessionAction@461c739c
[2016-01-04 11:14:33,813] [http-nio-8444-exec-7] [DEBUG] [com.....adminservices.webapp.ControllerServlet] Result: com.........webadmin.IgAdminActionResult@531398a0
[2016-01-04 11:14:33,817] [http-nio-8444-exec-7] [DEBUG] [com.....adminservices.webapp.ControllerServlet] Flow: com.....adminservices.webapp.ScreenFlow: nexturl=/show/Start/start nextop=com.....adminservices.webapp.view.NextOperation null/null
[2016-01-04 11:14:33,823] [http-nio-8444-exec-7] [DEBUG] [com.....adminservices.webapp.view.ViewServlet] View Operation: null.Start.start.null
[2016-01-04 11:14:33,823] [http-nio-8444-exec-7] [DEBUG] [com.....adminservices.webapp.view.ViewServlet] View: com.....adminservices.webapp.transform.TransformView xsl=login.xsl
[2016-01-04 11:14:33,829] [http-nio-8444-exec-7] [DEBUG] [com.....adminservices.webapp.transform.TransformView] Using XSL Parameters: host=rjayapralocal.dev.ad.....com:8444 igadmin.webServer=...Admin/web next-transaction=null req.context=/...Admin next-operation=null
[2016-01-04 11:14:33,829] [http-nio-8444-exec-7] [DEBUG] [com.....adminservices.webapp.transform.TransformView] Using content type: text/html; charset="utf-8"
[2016-01-04 11:14:33,829] [http-nio-8444-exec-7] [DEBUG] [com.....adminservices.webapp.transform.TransformView] Setting no-cache headers
[2016-01-04 11:14:35,360] [http-nio-8444-exec-7] [DEBUG] [org.stagemonitor.web.monitor.filter.HttpRequestMonitorFilter] atLeastServletApi3=true isHtmlRequested=false isAtLeastOneHtmlInjectorActive=true
[2016-01-04 11:14:39,808] [http-nio-8444-exec-8] [DEBUG] [org.stagemonitor.web.monitor.filter.HttpRequestMonitorFilter] atLeastServletApi3=true isHtmlRequested=false isAtLeastOneHtmlInjectorActive=true
[2016-01-04 11:14:39,808] [http-nio-8444-exec-8] [DEBUG] [org.stagemonitor.web.WebPlugin] isWidgetAndStagemonitorEndpointsAllowed: isWidgetEnabled=true, isPasswordInShowWidgetHeaderCorrect=false, result=true
```

This is the important part:
```
[2016-01-04 11:14:39,808] [http-nio-8444-exec-8] [DEBUG] [org.stagemonitor.web.monitor.filter.HttpRequestMonitorFilter] atLeastServletApi3=true isHtmlRequested=false isAtLeastOneHtmlInjectorActive=true
```

What's the URL for that? Could you send me a `.har` file for that url? Thats basically the information that you see when you inspect the page with Chrome developer tools as a json file. This is how you export a har file in Chrome:

<img width="556" alt="bildschirmfoto 2016-01-04 um 18 43 42" src="https://cloud.githubusercontent.com/assets/2163464/12096098/59006ff2-b313-11e5-961a-8ef86894d37b.png">


You can also debug around this line to see what goes wrong:
https://github.com/stagemonitor/stagemonitor/blob/36012286f4528bcadf56c82dd3b210a0f105ee21/stagemonitor-web/src/main/java/org/stagemonitor/web/monitor/filter/HttpRequestMonitorFilter.java#L143

**Comment by rathna82** [comment]
OMG I got the stage monitor icon in Chrome.. just not in IE .. All our testing is in IE so I never tried in Chrome until I tried to get your HAR.
Any Idea why this won't work in IE (11)?

**Comment by felixbarny** [comment]
Which version are you using? Probably ie isn't requesting text/html in the accept header. What is the ending of your urls? Maybe .xslt? Perhaps that's why the accept header is strange. Could you check which header ie is sending in the network tab?

**Comment by rathna82** [comment]
yeah that may be it.. Firefox and Chrome works good and they accept text-html
![image](https://cloud.githubusercontent.com/assets/16502814/12116418/b914ed7c-b387-11e5-8c48-a862e4b447de.png)

**Comment by felixbarny** [comment]
Could you tell me what the url looks like? Maybe I can reproduce it then.

**Comment by rathna82** [comment]
https://rjayapralocal.dev.ad.xxxx.com:8444/IdAdmin/do/Home
