### ISSUE TITLE
Unable to deploy stagemonitor-web on Weblogic 12c

### ISSUE THREAD

**Issue by elFarto** [stagemonitor/stagemonitor#145]
When attempting to deploy a WAR containing stagemonitor-web 0.22 onto a Weblogic 12c instance I get the following error:

```
<12-Apr-2016 16:45:06 o'clock BST> <Warning> <Deployer> <BEA-149078> <Stack trace for message 149004
weblogic.application.ModuleException: java.lang.NullPointerException
        at weblogic.application.internal.ExtensibleModuleWrapper.start(ExtensibleModuleWrapper.java:140)
        at weblogic.application.internal.flow.ModuleListenerInvoker.start(ModuleListenerInvoker.java:124)
        at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:237)
        at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:232)
        at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:45)
        Truncated. see log file for complete stacktrace
Caused By: java.lang.NullPointerException
        at org.stagemonitor.web.WebPlugin.onStartup(WebPlugin.java:378)
        at weblogic.servlet.internal.WebAppServletContext.initContainerInitializer(WebAppServletContext.java:1399)
        at weblogic.servlet.internal.WebAppServletContext.initContainerInitializers(WebAppServletContext.java:1359)
        at weblogic.servlet.internal.WebAppServletContext.initContainerInitializers(WebAppServletContext.java:1340)
        at weblogic.servlet.internal.WebAppServletContext.preloadResources(WebAppServletContext.java:1906)
        Truncated. see log file for complete stacktrace
```

This is because Weblogic already has a servlet registered with the name 'FileServlet', so attempting to add another causes it to return null.

**Comment by felixbarny** [comment]
Thx for reporting. This should be easy to fix.

**Comment by fatihturkeri** [comment]
I have faced same problem. How did you solve this problem. Could you help me, please.

**Comment by trampi** [comment]
@fatihturkeri Could you open a new issue and provide information about your environment, including exact Application Server version, version of stagemonitor, startup logs of stagemonitor, ...?
