### ISSUE TITLE
Deadlock on startup

### ISSUE THREAD

**Issue by domtoupin** [stagemonitor/stagemonitor#179]
When using stagemonitor with JBoss 5.1, we came across the following deadlock (relevant excerpt from jstack):

```
Found one Java-level deadlock:
=============================
"type-pool-cache-evicter":
  waiting to lock monitor 0x000000003b297f70 (object 0x00000007431b97d0, a org.jboss.classloader.spi.base.BaseClassLoader),
  which is held by "stagemonitor-startup"
"stagemonitor-startup":
  waiting to lock monitor 0x00000000157f92b0 (object 0x0000000740035c68, a org.jboss.bootstrap.NoAnnotationURLClassLoader),
  which is held by "main"
"main":
  waiting to lock monitor 0x000000003b297f70 (object 0x00000007431b97d0, a org.jboss.classloader.spi.base.BaseClassLoader),
  which is held by "stagemonitor-startup"

Java stack information for the threads listed above:
===================================================
"type-pool-cache-evicter":
	at org.stagemonitor.core.instrument.AutoEvictingCachingBinaryLocator$1.run(AutoEvictingCachingBinaryLocator.java:32)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:317)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:150)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.runPeriodic(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:204)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
"stagemonitor-startup":
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:249)
	at org.jboss.classloader.plugins.loader.ClassLoaderToLoaderAdapter.loadClass(ClassLoaderToLoaderAdapter.java:172)
	at org.jboss.classloader.spi.ClassLoaderDomain.loadClassFromParent(ClassLoaderDomain.java:352)
	at org.jboss.classloader.spi.ClassLoaderDomain.loadClassBefore(ClassLoaderDomain.java:307)
	at org.jboss.classloader.spi.base.BaseClassLoaderDomain.loadClass(BaseClassLoaderDomain.java:251)
	at org.jboss.classloader.spi.base.BaseClassLoaderDomain.loadClass(BaseClassLoaderDomain.java:1119)
	at org.jboss.classloader.spi.base.BaseClassLoader.loadClassFromDomain(BaseClassLoader.java:798)
	at org.jboss.classloader.spi.base.BaseClassLoader.loadClass(BaseClassLoader.java:441)
	- locked <0x00000007431b97d0> (a org.jboss.classloader.spi.base.BaseClassLoader)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at com.codahale.metrics.jvm.GarbageCollectorMetricSet.getMetrics(GarbageCollectorMetricSet.java:50)
	at org.stagemonitor.core.metrics.metrics2.Metric2Set$Converter$1.getMetrics(Metric2Set.java:33)
	at org.stagemonitor.core.metrics.metrics2.Metric2Registry.registerAll(Metric2Registry.java:78)
	at org.stagemonitor.jvm.JvmPlugin.initializePlugin(JvmPlugin.java:24)
	at org.stagemonitor.core.Stagemonitor.initializePlugin(Stagemonitor.java:137)
	at org.stagemonitor.core.Stagemonitor.initializePlugins(Stagemonitor.java:129)
	at org.stagemonitor.core.Stagemonitor.start(Stagemonitor.java:105)
	at org.stagemonitor.core.Stagemonitor.doStartMonitoring(Stagemonitor.java:93)
	- locked <0x00000007c5877850> (a java.lang.Class for org.stagemonitor.core.Stagemonitor)
	at org.stagemonitor.core.Stagemonitor.access$000(Stagemonitor.java:23)
	at org.stagemonitor.core.Stagemonitor$1.run(Stagemonitor.java:73)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
"main":
	at org.stagemonitor.core.instrument.AutoEvictingCachingBinaryLocator.locate(AutoEvictingCachingBinaryLocator.java:40)
	at net.bytebuddy.agent.builder.AgentBuilder$TypeLocator$WithTypePoolCache.typePool(AgentBuilder.java:1227)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:5683)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:5630)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:169)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:365)
	at java.lang.ClassLoader.findBootstrapClass(Native Method)
	at java.lang.ClassLoader.findBootstrapClassOrNull(ClassLoader.java:926)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:297)
	- locked <0x000000074001ecf8> (a sun.misc.Launcher$ExtClassLoader)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:295)
	- locked <0x000000074001fc08> (a sun.misc.Launcher$AppClassLoader)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	- locked <0x000000074001fc08> (a sun.misc.Launcher$AppClassLoader)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:295)
	- locked <0x0000000740035c68> (a org.jboss.bootstrap.NoAnnotationURLClassLoader)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:249)
	at org.jboss.classloader.plugins.loader.ClassLoaderToLoaderAdapter.loadClass(ClassLoaderToLoaderAdapter.java:172)
	at org.jboss.classloader.spi.ClassLoaderDomain.loadClassFromParent(ClassLoaderDomain.java:352)
	at org.jboss.classloader.spi.ClassLoaderDomain.loadClassBefore(ClassLoaderDomain.java:307)
	at org.jboss.classloader.spi.base.BaseClassLoaderDomain.loadClass(BaseClassLoaderDomain.java:251)
	at org.jboss.classloader.spi.base.BaseClassLoaderDomain.loadClass(BaseClassLoaderDomain.java:1119)
	at org.jboss.classloader.spi.base.BaseClassLoader.loadClassFromDomain(BaseClassLoader.java:798)
	at org.jboss.classloader.spi.base.BaseClassLoader.loadClass(BaseClassLoader.java:441)
	- locked <0x0000000742da5210> (a org.jboss.classloader.spi.base.BaseClassLoader)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at org.hsqldb.jdbcDriver.getConnection(Unknown Source)
	at org.hsqldb.jdbcDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:185)
	at org.jboss.jdbc.HypersonicDatabase.getConnection(HypersonicDatabase.java:777)
	- locked <0x00000006c4fd2a68> (a org.jboss.jdbc.HypersonicDatabase)
	at org.jboss.jdbc.HypersonicDatabase.startStandaloneDatabase(HypersonicDatabase.java:625)
	at org.jboss.jdbc.HypersonicDatabase.startService(HypersonicDatabase.java:568)
	at org.jboss.system.ServiceMBeanSupport.jbossInternalStart(ServiceMBeanSupport.java:376)
	at org.jboss.system.ServiceMBeanSupport.jbossInternalLifecycle(ServiceMBeanSupport.java:322)
	at sun.reflect.GeneratedMethodAccessor81.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.jboss.mx.interceptor.ReflectedDispatcher.invoke(ReflectedDispatcher.java:157)
	at org.jboss.mx.server.Invocation.dispatch(Invocation.java:96)
	at org.jboss.mx.server.Invocation.invoke(Invocation.java:88)
	at org.jboss.mx.server.AbstractMBeanInvoker.invoke(AbstractMBeanInvoker.java:264)
	at org.jboss.mx.server.MBeanServerImpl.invoke(MBeanServerImpl.java:668)
	at org.jboss.system.microcontainer.ServiceProxy.invoke(ServiceProxy.java:189)
	at com.sun.proxy.$Proxy38.start(Unknown Source)
	at org.jboss.system.microcontainer.StartStopLifecycleAction.installAction(StartStopLifecycleAction.java:42)
	at org.jboss.system.microcontainer.StartStopLifecycleAction.installAction(StartStopLifecycleAction.java:37)
	at org.jboss.dependency.plugins.action.SimpleControllerContextAction.simpleInstallAction(SimpleControllerContextAction.java:62)
	at org.jboss.dependency.plugins.action.AccessControllerContextAction.install(AccessControllerContextAction.java:71)
	at org.jboss.dependency.plugins.AbstractControllerContextActions.install(AbstractControllerContextActions.java:51)
	at org.jboss.dependency.plugins.AbstractControllerContext.install(AbstractControllerContext.java:348)
	at org.jboss.system.microcontainer.ServiceControllerContext.install(ServiceControllerContext.java:286)
	at org.jboss.dependency.plugins.AbstractController.install(AbstractController.java:1631)
	at org.jboss.dependency.plugins.AbstractController.incrementState(AbstractController.java:934)
	at org.jboss.dependency.plugins.AbstractController.resolveContexts(AbstractController.java:1082)
	at org.jboss.dependency.plugins.AbstractController.resolveContexts(AbstractController.java:984)
	at org.jboss.dependency.plugins.AbstractController.change(AbstractController.java:822)
	at org.jboss.dependency.plugins.AbstractController.change(AbstractController.java:553)
	at org.jboss.system.ServiceController.doChange(ServiceController.java:688)
	at org.jboss.system.ServiceController.start(ServiceController.java:460)
	at org.jboss.system.deployers.ServiceDeployer.start(ServiceDeployer.java:163)
	at org.jboss.system.deployers.ServiceDeployer.deploy(ServiceDeployer.java:99)
	at org.jboss.system.deployers.ServiceDeployer.deploy(ServiceDeployer.java:46)
	at org.jboss.deployers.spi.deployer.helpers.AbstractSimpleRealDeployer.internalDeploy(AbstractSimpleRealDeployer.java:62)
	at org.jboss.deployers.spi.deployer.helpers.AbstractRealDeployer.deploy(AbstractRealDeployer.java:50)
	at org.jboss.deployers.plugins.deployers.DeployerWrapper.deploy(DeployerWrapper.java:171)
	at org.jboss.deployers.plugins.deployers.DeployersImpl.doDeploy(DeployersImpl.java:1439)
	at org.jboss.deployers.plugins.deployers.DeployersImpl.doInstallParentFirst(DeployersImpl.java:1157)
	at org.jboss.deployers.plugins.deployers.DeployersImpl.doInstallParentFirst(DeployersImpl.java:1178)
	at org.jboss.deployers.plugins.deployers.DeployersImpl.install(DeployersImpl.java:1098)
	at org.jboss.dependency.plugins.AbstractControllerContext.install(AbstractControllerContext.java:348)
	at org.jboss.dependency.plugins.AbstractController.install(AbstractController.java:1631)
	at org.jboss.dependency.plugins.AbstractController.incrementState(AbstractController.java:934)
	at org.jboss.dependency.plugins.AbstractController.resolveContexts(AbstractController.java:1082)
	at org.jboss.dependency.plugins.AbstractController.resolveContexts(AbstractController.java:984)
	at org.jboss.dependency.plugins.AbstractController.change(AbstractController.java:822)
	at org.jboss.dependency.plugins.AbstractController.change(AbstractController.java:553)
	at org.jboss.deployers.plugins.deployers.DeployersImpl.process(DeployersImpl.java:781)
	at org.jboss.deployers.plugins.main.MainDeployerImpl.process(MainDeployerImpl.java:702)
	at org.jboss.system.server.profileservice.repository.MainDeployerAdapter.process(MainDeployerAdapter.java:117)
	at org.jboss.system.server.profileservice.repository.ProfileDeployAction.install(ProfileDeployAction.java:70)
	at org.jboss.system.server.profileservice.repository.AbstractProfileAction.install(AbstractProfileAction.java:53)
	at org.jboss.system.server.profileservice.repository.AbstractProfileService.install(AbstractProfileService.java:361)
	at org.jboss.dependency.plugins.AbstractControllerContext.install(AbstractControllerContext.java:348)
	at org.jboss.dependency.plugins.AbstractController.install(AbstractController.java:1631)
	at org.jboss.dependency.plugins.AbstractController.incrementState(AbstractController.java:934)
	at org.jboss.dependency.plugins.AbstractController.resolveContexts(AbstractController.java:1082)
	at org.jboss.dependency.plugins.AbstractController.resolveContexts(AbstractController.java:984)
	at org.jboss.dependency.plugins.AbstractController.change(AbstractController.java:822)
	at org.jboss.dependency.plugins.AbstractController.change(AbstractController.java:553)
	at org.jboss.system.server.profileservice.repository.AbstractProfileService.activateProfile(AbstractProfileService.java:306)
	at org.jboss.system.server.profileservice.ProfileServiceBootstrap.start(ProfileServiceBootstrap.java:271)
	at org.jboss.bootstrap.AbstractServerImpl.start(AbstractServerImpl.java:461)
	at org.jboss.Main.boot(Main.java:221)
	at org.jboss.Main$1.run(Main.java:556)
	at java.lang.Thread.run(Thread.java:662)

Found 1 deadlock.
```

Any chance this can be fixed?

**Comment by domtoupin** [comment]
Another deadlock report:

```
Found one Java-level deadlock:
=============================
"stagemonitor-startup":
  waiting to lock monitor 0x00007fe8641734e8 (object 0x00000000ac1b3328, a org.jboss.bootstrap.NoAnnotationURLClassLoader),
  which is held by "main"
"main":
  waiting to lock monitor 0x00007fe864173440 (object 0x00000000afec6378, a org.jboss.classloader.spi.base.BaseClassLoader),
  which is held by "stagemonitor-startup"

Java stack information for the threads listed above:
===================================================
"stagemonitor-startup":
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:249)
	at org.jboss.classloader.plugins.loader.ClassLoaderToLoaderAdapter.loadClass(ClassLoaderToLoaderAdapter.java:172)
	at org.jboss.classloader.spi.ClassLoaderDomain.loadClassFromParent(ClassLoaderDomain.java:352)
	at org.jboss.classloader.spi.ClassLoaderDomain.loadClassBefore(ClassLoaderDomain.java:307)
	at org.jboss.classloader.spi.base.BaseClassLoaderDomain.loadClass(BaseClassLoaderDomain.java:251)
	at org.jboss.classloader.spi.base.BaseClassLoaderDomain.loadClass(BaseClassLoaderDomain.java:1119)
	at org.jboss.classloader.spi.base.BaseClassLoader.loadClassFromDomain(BaseClassLoader.java:798)
	at org.jboss.classloader.spi.base.BaseClassLoader.loadClass(BaseClassLoader.java:441)
	- locked <0x00000000afec6378> (a org.jboss.classloader.spi.base.BaseClassLoader)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at org.stagemonitor.core.util.JsonUtils.<clinit>(JsonUtils.java:21)
	at org.stagemonitor.core.elasticsearch.ElasticsearchClient.requireBoxTypeHotIfHotColdAritectureActive(ElasticsearchClient.java:179)
	at org.stagemonitor.requestmonitor.RequestMonitorPlugin.initializePlugin(RequestMonitorPlugin.java:307)
	at org.stagemonitor.core.Stagemonitor.initializePlugin(Stagemonitor.java:137)
	at org.stagemonitor.core.Stagemonitor.initializePlugins(Stagemonitor.java:129)
	at org.stagemonitor.core.Stagemonitor.start(Stagemonitor.java:105)
	at org.stagemonitor.core.Stagemonitor.doStartMonitoring(Stagemonitor.java:93)
	- locked <0x00000000ed8ca9f8> (a java.lang.Class for org.stagemonitor.core.Stagemonitor)
	at org.stagemonitor.core.Stagemonitor.access$000(Stagemonitor.java:23)
	at org.stagemonitor.core.Stagemonitor$1.run(Stagemonitor.java:73)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
"main":
	at org.stagemonitor.core.instrument.AutoEvictingCachingBinaryLocator.locate(AutoEvictingCachingBinaryLocator.java:40)
	at net.bytebuddy.agent.builder.AgentBuilder$TypeLocator$WithTypePoolCache.typePool(AgentBuilder.java:1227)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:5683)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:5630)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:169)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:365)
	at java.lang.ClassLoader.findBootstrapClass(Native Method)
	at java.lang.ClassLoader.findBootstrapClassOrNull(ClassLoader.java:926)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:297)
	- locked <0x00000000ac316980> (a sun.misc.Launcher$ExtClassLoader)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:295)
	- locked <0x00000000ac1b32e0> (a sun.misc.Launcher$AppClassLoader)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	- locked <0x00000000ac1b32e0> (a sun.misc.Launcher$AppClassLoader)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:295)
	- locked <0x00000000ac1b3328> (a org.jboss.bootstrap.NoAnnotationURLClassLoader)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:249)
	at org.jboss.classloader.plugins.loader.ClassLoaderToLoaderAdapter.loadClass(ClassLoaderToLoaderAdapter.java:172)
	at org.jboss.classloader.spi.ClassLoaderDomain.loadClassFromParent(ClassLoaderDomain.java:352)
	at org.jboss.classloader.spi.ClassLoaderDomain.loadClassBefore(ClassLoaderDomain.java:307)
	at org.jboss.classloader.spi.base.BaseClassLoaderDomain.loadClass(BaseClassLoaderDomain.java:251)
	at org.jboss.classloader.spi.base.BaseClassLoaderDomain.loadClass(BaseClassLoaderDomain.java:1119)
	at org.jboss.classloader.spi.base.BaseClassLoader.loadClassFromDomain(BaseClassLoader.java:798)
	at org.jboss.classloader.spi.base.BaseClassLoader.loadClass(BaseClassLoader.java:441)
	- locked <0x00000000ae8ee3a0> (a org.jboss.classloader.spi.base.BaseClassLoader)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at org.hsqldb.jdbcDriver.getConnection(Unknown Source)
	at org.hsqldb.jdbcDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:185)
	at org.jboss.jdbc.HypersonicDatabase.getConnection(HypersonicDatabase.java:777)
	- locked <0x00000000bda8dca8> (a org.jboss.jdbc.HypersonicDatabase)
	at org.jboss.jdbc.HypersonicDatabase.startStandaloneDatabase(HypersonicDatabase.java:625)
	at org.jboss.jdbc.HypersonicDatabase.startService(HypersonicDatabase.java:568)
	at org.jboss.system.ServiceMBeanSupport.jbossInternalStart(ServiceMBeanSupport.java:376)
	at org.jboss.system.ServiceMBeanSupport.jbossInternalLifecycle(ServiceMBeanSupport.java:322)
	at sun.reflect.GeneratedMethodAccessor81.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.jboss.mx.interceptor.ReflectedDispatcher.invoke(ReflectedDispatcher.java:157)
	at org.jboss.mx.server.Invocation.dispatch(Invocation.java:96)
	at org.jboss.mx.server.Invocation.invoke(Invocation.java:88)
	at org.jboss.mx.server.AbstractMBeanInvoker.invoke(AbstractMBeanInvoker.java:264)
	at org.jboss.mx.server.MBeanServerImpl.invoke(MBeanServerImpl.java:668)
	at org.jboss.system.microcontainer.ServiceProxy.invoke(ServiceProxy.java:189)
	at com.sun.proxy.$Proxy38.start(Unknown Source)
	at org.jboss.system.microcontainer.StartStopLifecycleAction.installAction(StartStopLifecycleAction.java:42)
	at org.jboss.system.microcontainer.StartStopLifecycleAction.installAction(StartStopLifecycleAction.java:37)
	at org.jboss.dependency.plugins.action.SimpleControllerContextAction.simpleInstallAction(SimpleControllerContextAction.java:62)
	at org.jboss.dependency.plugins.action.AccessControllerContextAction.install(AccessControllerContextAction.java:71)
	at org.jboss.dependency.plugins.AbstractControllerContextActions.install(AbstractControllerContextActions.java:51)
	at org.jboss.dependency.plugins.AbstractControllerContext.install(AbstractControllerContext.java:348)
	at org.jboss.system.microcontainer.ServiceControllerContext.install(ServiceControllerContext.java:286)
	at org.jboss.dependency.plugins.AbstractController.install(AbstractController.java:1631)
	at org.jboss.dependency.plugins.AbstractController.incrementState(AbstractController.java:934)
	at org.jboss.dependency.plugins.AbstractController.resolveContexts(AbstractController.java:1082)
	at org.jboss.dependency.plugins.AbstractController.resolveContexts(AbstractController.java:984)
	at org.jboss.dependency.plugins.AbstractController.change(AbstractController.java:822)
	at org.jboss.dependency.plugins.AbstractController.change(AbstractController.java:553)
	at org.jboss.system.ServiceController.doChange(ServiceController.java:688)
	at org.jboss.system.ServiceController.start(ServiceController.java:460)
	at org.jboss.system.deployers.ServiceDeployer.start(ServiceDeployer.java:163)
	at org.jboss.system.deployers.ServiceDeployer.deploy(ServiceDeployer.java:99)
	at org.jboss.system.deployers.ServiceDeployer.deploy(ServiceDeployer.java:46)
	at org.jboss.deployers.spi.deployer.helpers.AbstractSimpleRealDeployer.internalDeploy(AbstractSimpleRealDeployer.java:62)
	at org.jboss.deployers.spi.deployer.helpers.AbstractRealDeployer.deploy(AbstractRealDeployer.java:50)
	at org.jboss.deployers.plugins.deployers.DeployerWrapper.deploy(DeployerWrapper.java:171)
	at org.jboss.deployers.plugins.deployers.DeployersImpl.doDeploy(DeployersImpl.java:1439)
	at org.jboss.deployers.plugins.deployers.DeployersImpl.doInstallParentFirst(DeployersImpl.java:1157)
	at org.jboss.deployers.plugins.deployers.DeployersImpl.doInstallParentFirst(DeployersImpl.java:1178)
	at org.jboss.deployers.plugins.deployers.DeployersImpl.install(DeployersImpl.java:1098)
	at org.jboss.dependency.plugins.AbstractControllerContext.install(AbstractControllerContext.java:348)
	at org.jboss.dependency.plugins.AbstractController.install(AbstractController.java:1631)
	at org.jboss.dependency.plugins.AbstractController.incrementState(AbstractController.java:934)
	at org.jboss.dependency.plugins.AbstractController.resolveContexts(AbstractController.java:1082)
	at org.jboss.dependency.plugins.AbstractController.resolveContexts(AbstractController.java:984)
	at org.jboss.dependency.plugins.AbstractController.change(AbstractController.java:822)
	at org.jboss.dependency.plugins.AbstractController.change(AbstractController.java:553)
	at org.jboss.deployers.plugins.deployers.DeployersImpl.process(DeployersImpl.java:781)
	at org.jboss.deployers.plugins.main.MainDeployerImpl.process(MainDeployerImpl.java:702)
	at org.jboss.system.server.profileservice.repository.MainDeployerAdapter.process(MainDeployerAdapter.java:117)
	at org.jboss.system.server.profileservice.repository.ProfileDeployAction.install(ProfileDeployAction.java:70)
	at org.jboss.system.server.profileservice.repository.AbstractProfileAction.install(AbstractProfileAction.java:53)
	at org.jboss.system.server.profileservice.repository.AbstractProfileService.install(AbstractProfileService.java:361)
	at org.jboss.dependency.plugins.AbstractControllerContext.install(AbstractControllerContext.java:348)
	at org.jboss.dependency.plugins.AbstractController.install(AbstractController.java:1631)
	at org.jboss.dependency.plugins.AbstractController.incrementState(AbstractController.java:934)
	at org.jboss.dependency.plugins.AbstractController.resolveContexts(AbstractController.java:1082)
	at org.jboss.dependency.plugins.AbstractController.resolveContexts(AbstractController.java:984)
	at org.jboss.dependency.plugins.AbstractController.change(AbstractController.java:822)
	at org.jboss.dependency.plugins.AbstractController.change(AbstractController.java:553)
	at org.jboss.system.server.profileservice.repository.AbstractProfileService.activateProfile(AbstractProfileService.java:306)
	at org.jboss.system.server.profileservice.ProfileServiceBootstrap.start(ProfileServiceBootstrap.java:271)
	at org.jboss.bootstrap.AbstractServerImpl.start(AbstractServerImpl.java:461)
	at org.jboss.Main.boot(Main.java:221)
	at org.jboss.Main$1.run(Main.java:556)
	at java.lang.Thread.run(Thread.java:662)

Found 1 deadlock.
```

**Comment by felixbarny** [comment]
Thx for reporting. It's important for me to know which stagemonitor version and jboss version you are using.

**Comment by felixbarny** [comment]
@raphw: My suspicion is that this deadlock could be caused by accessing `BootstrapClassLoaderMarker.INSTANCE` which creates a new ClassLoader on initialization. Do you think that could be possible? See https://github.com/stagemonitor/stagemonitor/blob/0.26.1/stagemonitor-core/src/main/java/org/stagemonitor/core/instrument/AutoEvictingCachingBinaryLocator.java#L40

FYI: stagemonitor-startup is a thread which concurrently initializes the stagemonitor plugins on server startup. One way to avoid this deadlock might be to init BootstrapClassLoaderMarker.INSTANCE on the main thread so that is already initialized when accessed by stagemonitor-startup. Another option would be to use a different class loader to denote the bootstrap class loader (maybe `ClassLoader.getSystemClassLoader().getParent()`?).

**Comment by felixbarny** [comment]
@domtoupin Which exact java version are you using? That may be of importance as well.

**Comment by raphw** [comment]
@felixbarny To me, this looks like a typical class loading lock. In the above case the *main* thread is triggering a transformer. When a transformer is triggered, the entire class loader hierarchy is locked to avoid that two classes attempt loading the same class simultaneously.

At the same time, the *stagemonitor-startup* thread is attempting to load *JsonUtils* which requires locking that thread's class loader for loading. 

Typically, this does not cause a dead-lock as class loaders are fully hierarchical. However, in this case, JBoss enforces child-first class loading and triggers a class loading via the same class loader hierarchy as from *stagemonitor-startup*. This one is already locked. At the same time, *stagemonitor-startup* is waiting for the latter class loader.

I would go so far as of blaming JBoss here. It seems to assume control of the system class loader which is broken for using a Java agent.

As for a resolution: I just replaced the marker class loader with simply using the system class loader. Byte Buddy needs to call methods on a `ClassLoader` to read resources and in generally, Byte Buddy already uses the system class loader whenever the bootstrap class loader is found. This way, it makes sense to use the system class loader as a cache key as well.

**Comment by domtoupin** [comment]
@felixbarny Here are the versions we use:

- JBoss 5.1
- Stagemonitor 0.26.1
- Java 6 (Oracle "1.6.0_45")

**Comment by felixbarny** [comment]
Thanks for another great analysis! Where can I read more about when class loaders are locked? What I don't quite understand is how the creation of the bootstrap class loader marker class was causing this. After the issue with the marker class is fixed, is there any chance of related deadlocks? Is it a bad idea to asynchronously init stagemonitor because of possible deadlocks?

**Comment by raphw** [comment]
It is basically how any class is loaded, have a look at the `ClassLoader` implementation: http://grepcode.com/file_/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/java/lang/ClassLoader.java/?v=source

**Comment by felixbarny** [comment]
Stagemonitor tries to register it's transformers as soon as possible to avoid expensive retransformations. I think in this instance the best solution is to disable async initialization by default and add a feature flag to enable it with a warning about possible deadlocks.

**Comment by raphw** [comment]
Sounds like a good idea. In a default application, it should not be a problem but class loaders are tricky to implement and especially the JBoss class loader is very tricky to work with.
