### ISSUE TITLE
SecurityException occured when try to attaches byte-byte-agent

### ISSUE THREAD

**Issue by Jack47** [stagemonitor/stagemonitor#204]
I run tomcat on docker based on [this tomcat 8 image](https://github.com/docker-library/tomcat/blob/81c66e2e695ad5548b726841c00512a9acf18eb5/8.0/jre7/Dockerfile), SecurityException occured when sm try to attaches byte-byte-agent.
I already add `-javaagent:xxx`, as displayed by tomcat startup command:
```
/usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager `-javaagent:/usr/local/tomcat/webapps/okr/WEB-INF/lib/byte-buddy-agent-1.3.19.jar` -Djava.endorsed.dirs=/usr/local/tomcat/endorsed -classpath /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar -Dcatalina.base=/usr/local/tomcat -Dcatalina.home=/usr/local/tomcat -Djava.io.tmpdir=/usr/local/tomcat/temp org.apache.catalina.startup.Bootstrap start
``` 

```
#java -version
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-1~deb8u1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
```
startup log:
```
2016-10-11 15:12:58 WARN  AgentAttacher:111 - Failed to perform runtime attachment of the stagemonitor agent. Make sure that you run your application with a JDK (not a JRE).To make stagemonitor work with a JRE, you have to add the following command line argument to the start of the JVM: -javaagent:/path/to/byte-buddy-agent-<version>.jar
java.lang.SecurityException: Prohibited package name: java.lang.stagemonitor.dispatcher
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:658)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:794)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2503)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:831)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1274)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1139)
	at org.stagemonitor.core.instrument.AgentAttacher.initInstrumentation(AgentAttacher.java:105)
	at org.stagemonitor.core.instrument.AgentAttacher.performRuntimeAttachment(AgentAttacher.java:75)
	at org.stagemonitor.core.Stagemonitor.reset(Stagemonitor.java:246)
	at org.stagemonitor.core.Stagemonitor.<clinit>(Stagemonitor.java:39)
	at org.stagemonitor.web.WebPlugin.<clinit>(WebPlugin.java:56)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:278)
	at org.apache.catalina.startup.WebappServiceLoader.loadServices(WebappServiceLoader.java:186)
	at org.apache.catalina.startup.WebappServiceLoader.load(WebappServiceLoader.java:157)
	at org.apache.catalina.startup.ContextConfig.processServletContainerInitializers(ContextConfig.java:1620)
	at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1136)
	at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:779)
	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:306)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:95)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5150)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1092)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1834)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by felixbarny** [comment]
Thx for creating this issue. Due to a non spec compliant behaviour of the JBoss Classloader, i had to place a class inside the java.lang.stagemonitor.dispatcher package. The security manager apparently prevents this by throwing a SecurityException. The quick fix would be to disable the security manager. I'll look into alternatives of placing the classes inside the java package.

**Comment by felixbarny** [comment]
Looks like it does not have to do with the SecurityManager though

**Comment by Jack47** [comment]
I finally figured out that stagemonitor doesn't works well with tomcat 8. It works well with tomcat 7.

**Comment by felixbarny** [comment]
That's good to know. I'll add tomcat 8 tests then. Also, I've fixed the source of the SecurityException (see 80793ac6c582944c9078b420138dda4d23517a69). I hope this is everything that is needed for the tomcat 8 support.

**Comment by felixbarny** [comment]
Actually, stagemonitor is already integration-tested with tomcat 8 so this is quite strange... Also the Dockerfile you have linked is the one for tomcat 7. Which tomcat 8 version did you try? I'm currently testing with 8.0.24: https://github.com/stagemonitor/stagemonitor-integration-tests/blob/master/servers.gradle#L67

**Comment by felixbarny** [comment]
The latest version 8.0.38 is also working fine. So maybe it is the way the docker container is set up. But hopefully my commit fixes the issue altogether.

**Comment by felixbarny** [comment]
Which stagemonitor version are you using?

**Comment by Jack47** [comment]
I'm using stagemonitor based on version 0.25.0.

**Comment by felixbarny** [comment]
Is it possible that you declared a compile dependency to stagemonitor-dispatcher? If not, could you help me to reproduce the exception?

**Comment by felixbarny** [comment]
I'll pobably revert the last commit as that is not the source of the problem. The real question is why this class was loaded by Tomcat's class loader and not the bootstrap classloader.

**Comment by Jack47** [comment]
I didn't declared a compile dependency to stagemonitor-dispatcher. This exception disappeared after I apply the commit 80793ac
