### ISSUE TITLE
Error when running the OSPlugin Test

### ISSUE THREAD

**Issue by SyCode7** [stagemonitor/stagemonitor#241]
I want to use stagemonitor to get some OS metrics, CPU metrics to be more specific. While running the OSPlugin test class, I have the error : 
`If you see this exception inside you IDE, you have to execute gradle processResources before running the tests` . 

My interpretation is that I have to run the `gradle processResources` command in the command line however the error still appears even after I run this command. Please is there somethin I am missing ?  Thanks.

**Comment by felixbarny** [comment]
The `FileCollectionSnapshotterRegistry` error seems really strange. I have never seen it before. Is there any stack trace? Do the tests work when executing `./gradlew clean test` on the command line?

**Comment by SyCode7** [comment]
./gradlew clean test fails at the coreplugin test, see stacktrace below 

`
test@test-virtual-machine:~/git/stagemonitor$ ./gradlew clean test
Incremental java compilation is an incubating feature.
Defining custom 'build' task when using the standard Gradle lifecycle plugins has been deprecated and is scheduled to be removed in Gradle 3.0
:clean UP-TO-DATE
:stagemonitor-alerting:clean
:stagemonitor-benchmark:clean UP-TO-DATE
:stagemonitor-core:clean
:stagemonitor-dispatcher:clean
:stagemonitor-ehcache:clean UP-TO-DATE
:stagemonitor-grafana-elasticsearch:clean UP-TO-DATE
:stagemonitor-jdbc:clean UP-TO-DATE
:stagemonitor-jvm:clean UP-TO-DATE
:stagemonitor-logging:clean UP-TO-DATE
:stagemonitor-os:clean UP-TO-DATE
:stagemonitor-requestmonitor:clean
:stagemonitor-web:clean UP-TO-DATE
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:instrument SKIPPED
:copyCoberturaDatafile SKIPPED
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:stagemonitor-dispatcher:compileJava
:stagemonitor-dispatcher:compileJava - is not incremental (e.g. outputs have changed, no previous execution, etc.).
warning: [options] bootstrap class path not set in conjunction with -source 1.6
1 warning
:stagemonitor-dispatcher:processResources UP-TO-DATE
:stagemonitor-dispatcher:classes
:stagemonitor-dispatcher:jar
:stagemonitor-core:compileJava
:stagemonitor-core:compileJava - is not incremental (e.g. outputs have changed, no previous execution, etc.).
warning: [options] bootstrap class path not set in conjunction with -source 1.6
/home/test/git/stagemonitor/stagemonitor-core/src/main/java/org/stagemonitor/core/instrument/CallerUtil.java:7: warning: JavaLangAccess is internal proprietary API and may be removed in a future release
import sun.misc.JavaLangAccess;
               ^
/home/test/git/stagemonitor/stagemonitor-core/src/main/java/org/stagemonitor/core/instrument/CallerUtil.java:8: warning: SharedSecrets is internal proprietary API and may be removed in a future release
import sun.misc.SharedSecrets;
               ^
/home/test/git/stagemonitor/stagemonitor-core/src/main/java/org/stagemonitor/core/instrument/CallerUtil.java:16: warning: SharedSecrets is internal proprietary API and may be removed in a future release
                        javaLangAccessObject = SharedSecrets.getJavaLangAccess();
                                               ^
/home/test/git/stagemonitor/stagemonitor-core/src/main/java/org/stagemonitor/core/instrument/CallerUtil.java:42: warning: JavaLangAccess is internal proprietary API and may be removed in a future release
                final JavaLangAccess javaLangAccess = (JavaLangAccess) javaLangAccessObject;
                      ^
/home/test/git/stagemonitor/stagemonitor-core/src/main/java/org/stagemonitor/core/instrument/CallerUtil.java:42: warning: JavaLangAccess is internal proprietary API and may be removed in a future release
                final JavaLangAccess javaLangAccess = (JavaLangAccess) javaLangAccessObject;
                                                       ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
6 warnings
:stagemonitor-core:processResources
:stagemonitor-core:classes
:stagemonitor-core:jar
:stagemonitor-requestmonitor:compileJava
:stagemonitor-requestmonitor:compileJava - is not incremental (e.g. outputs have changed, no previous execution, etc.).
warning: [options] bootstrap class path not set in conjunction with -source 1.6
Note: /home/test/git/stagemonitor/stagemonitor-requestmonitor/src/main/java/org/stagemonitor/requestmonitor/freemarker/FreemarkerProfilingTransformer.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
:stagemonitor-requestmonitor:processResources
:stagemonitor-requestmonitor:classes
:stagemonitor-requestmonitor:jar
:stagemonitor-alerting:compileJava
:stagemonitor-alerting:compileJava - is not incremental (e.g. outputs have changed, no previous execution, etc.).
warning: [options] bootstrap class path not set in conjunction with -source 1.6
Note: /home/test/git/stagemonitor/stagemonitor-alerting/src/main/java/org/stagemonitor/alerting/ThresholdMonitoringReporter.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
:stagemonitor-alerting:processResources
:stagemonitor-alerting:classes
:stagemonitor-alerting:instrument SKIPPED
:stagemonitor-alerting:copyCoberturaDatafile SKIPPED
:stagemonitor-core:compileTestJava
:stagemonitor-core:compileTestJava - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/test/git/stagemonitor/stagemonitor-core/src/test/java/org/stagemonitor/core/metrics/metrics2/Metric2RegistryTest.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:stagemonitor-core:processTestResources
:stagemonitor-core:testClasses
:stagemonitor-alerting:compileTestJava
:stagemonitor-alerting:compileTestJava - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:stagemonitor-alerting:processTestResources
:stagemonitor-alerting:testClasses
:stagemonitor-alerting:test
:stagemonitor-core:instrument SKIPPED
:stagemonitor-core:copyCoberturaDatafile SKIPPED
:stagemonitor-core:test

org.stagemonitor.core.metrics.annotations.GaugeInstrumenterTest > testGaugeAspectDefault FAILED
    java.lang.AssertionError: expected:<5> but was:<6>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at org.stagemonitor.core.metrics.annotations.GaugeInstrumenterTest.testGaugeAspectDefault(GaugeInstrumenterTest.java:29)

213 tests completed, 1 failed, 1 skipped
:stagemonitor-core:test FAILED
:stagemonitor-alerting:generateCoberturaReport SKIPPED
:stagemonitor-alerting:performCoverageCheck SKIPPED
:stagemonitor-core:generateCoberturaReport SKIPPED
:stagemonitor-core:performCoverageCheck SKIPPED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':stagemonitor-core:test'.
> There were failing tests. See the report at: file:///home/test/git/stagemonitor/stagemonitor-core/build/reports/tests/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 23.717 secs `

**Comment by felixbarny** [comment]
Are you sure you have checked out the current master branch? The tests work on my machine and on travis. Could you share some details of your environment like OS, Java version, which kind of JVM, ...?

**Comment by SyCode7** [comment]
HI, I just x-checked to be sure , I can confim that I am currently on the master branch 
`7a0bc80b066edb9bb1b3e2f65cd13661abb4ef28`.
Here are the details for my environment - Eclipse IDE ,
`java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)`

`lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
`

**Comment by felixbarny** [comment]
If you happen to find out the issue please tell me the cause. Otherwise, in order to test the OS-plugin you don't have to build stagemonitor yourself or execute the tests. See https://github.com/stagemonitor/stagemonitor/wiki/Collect-Operating-System-Metrics

**Comment by SyCode7** [comment]
Hi thanks, I just went through the link but I have a few questions.  How possible is it to directly set a CPU threshold  e.g. cpu-idle time as a trigger (or Alarm) using the OS-Plugin web integration approach mentioned in the link you gave above. Like, can the web application derive the metrics directly or queries have to be made against elasticsearch in the backend.

**Comment by felixbarny** [comment]
> How possible is it to directly set a CPU threshold e.g. cpu-idle time as a trigger (or Alarm) 

You mean with `stagemonitor-alterting`? You can set the thresholds in the alters tab of the in browser widget. The thresholds are evaluated against the local metric registry so it also works without any Elasticsearch server.

**Comment by SyCode7** [comment]
Sorry, I am not sure I understand what you meant, are you referring to the "Alerts button" ?  Will there be the possibility of programmatically acquiring that information somehow ? If you direct me to the appropriate classes ?

**Comment by felixbarny** [comment]
This is what I mean: https://github.com/stagemonitor/stagemonitor/wiki/Alerting (I just added 2 screenshots to this site). 

>  Will there be the possibility of programmatically acquiring that information somehow

Which information and what do you want to do with it?

**Comment by SyCode7** [comment]
Oh, I see. I am actually working on some loadbalancing schemes for cloud instances (OpenStack). I thought with  stagemonitor, I could monitor the cpu metrics on each instance and thereby spawn or kill instances when certain thresholds are reached. I have looked at the standalone deployment approach but it seems the results are sent to elasticsearch directly. I could try using Sigar API, but  it is already an integral part of stagemonitor.

**Comment by felixbarny** [comment]
I see! You could implement your own [Alerter](https://github.com/stagemonitor/stagemonitor/blob/master/stagemonitor-alerting/src/main/java/org/stagemonitor/alerting/alerter/Alerter.java) which is like an on threshold breached callback. 

> I have looked at the standalone deployment approach but it seems the results are sent to elasticsearch directly

Not sure what you mean by that. You have problems with the standalone setup?

**Comment by SyCode7** [comment]
Thanks a lot for your answers, I do not have problems with the standalone set-up, I was just trying to compare which better in my use case. Will let you know if i have any challenges in implementing custom alerts. 👍
