### ISSUE TITLE
gradle build problem

### ISSUE THREAD

**Issue by songlong** [stagemonitor/stagemonitor#247]
hi:
    install problem??

org.stagemonitor.core.elasticsearch.IndexSelectorIntegrationTest > testDeleteOldIndicesUnavailable FAILED
    java.lang.AssertionError: expected:<[stagemonitor-metrics-1970.01.10, stagemonitor-metrics-1970.01.09]> but was:<[stagemonitor-metrics-1970.01.09]>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at org.stagemonitor.core.elasticsearch.IndexSelectorIntegrationTest.testDeleteOldIndicesUnavailable(IndexSelectorIntegrationTest.java:50)

214 tests completed, 1 failed, 1 skipped
:stagemonitor-core:test FAILED
:stagemonitor-core:generateCoberturaReport SKIPPED
:stagemonitor-core:performCoverageCheck SKIPPED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':stagemonitor-core:test'.
> There were failing tests. See the report at: file:///home/ysl/elk/stagemonitor/stagemonitor-core/build/reports/tests/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by felixbarny** [comment]
The tests are running fine on Travis and on my machine so I think this issue is specific to your machine.

Is this error reprocudcible? Could you share some details of your os?

Hm, maybe it is your time zone setting which causes the issue! Could you try the tests on a coworker's machine? What is your time zone?

**Comment by songlong** [comment]
system: centos7
java： 1.8
Linux version 3.10.0-514.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Tue Nov 22 16:42:41 UTC 2016
Thu, 16 Feb 2017 14:25:13 +
time zone: china/Shanghai 
how to  set time zone?

**Comment by felixbarny** [comment]
See http://stackoverflow.com/a/2493805/1125055

**Comment by songlong** [comment]
just now I change time zone but i happened error above?
I found use ./gradlew build happed error?

so when I use commnd " ./gradlew install " is is ok?

tag cannot be used in method with void return type.
1 warning
:stagemonitor-web:javadocJar
:stagemonitor-web:sourcesJar
:stagemonitor-web:signArchives SKIPPED
:stagemonitor-web:install

BUILD SUCCESSFUL

Total time: 24.551 secs
