### ISSUE TITLE
Problems during container shutdown

### ISSUE THREAD

**Issue by hrzbrg** [stagemonitor/stagemonitor#302]
Hi,

we are running Stagemonitor in our Docker containers. The containers run a Tomcat with our service .wars in it. In the container we have a lifecycle listener https://github.com/knatsakis/tc-init-health-check-listener to shut down the container, if the webapp does not load properly.

Recently we saw an issue with an unhealthy webapp where the above healthcheck listener initiated a shutdown. Unfortunately the shutdown hangs and only prints the following lines forever and the container does not die:

```
Aug 15, 2017 11:26:54 PM org.apache.catalina.loader.WebappClassLoaderBase checkStateForResourceLoading
INFO: Illegal access: this web application instance has been stopped already. Could not load [stagemonitor.properties]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [stagemonitor.properties]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1353)
	at org.apache.catalina.loader.WebappClassLoaderBase.getResourceAsStream(WebappClassLoaderBase.java:1088)
	at org.stagemonitor.configuration.source.PropertyFileConfigurationSource.getFromClasspath(PropertyFileConfigurationSource.java:74)
	at org.stagemonitor.configuration.source.PropertyFileConfigurationSource.getProperties(PropertyFileConfigurationSource.java:65)
	at org.stagemonitor.configuration.source.PropertyFileConfigurationSource.reload(PropertyFileConfigurationSource.java:40)
	at org.stagemonitor.configuration.ConfigurationRegistry.reload(ConfigurationRegistry.java:264)
	at org.stagemonitor.configuration.ConfigurationRegistry.reloadDynamicConfigurationOptions(ConfigurationRegistry.java:258)
	at org.stagemonitor.configuration.ConfigurationRegistry$3.run(ConfigurationRegistry.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by trampi** [comment]
I will have a look at this later this day. Thanks for reporting and sorry for the trouble.

**Comment by trampi** [comment]
I am not completely sure what could lead to this yet.

**Comment by felixbarny** [comment]
Does the shutdown also hang when stagemonitor is disabled? Could you send me a stack trace of the application (via `kill -3` or `jstack`)? How do you shutdown the Tomcat server?

**Comment by ychandu** [comment]
I am also facing similar issue , here is the stack trace.
java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [stagemonitor.properties]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1311) ~[?:?] 
at org.apache.catalina.loader.WebappClassLoaderBase.getResourceAsStream(WebappClassLoaderBase.java:1045) ~[?:?]
        at org.stagemonitor.configuration.source.PropertyFileConfigurationSource.getFromClasspath(PropertyFileConfigurationSource.java:74) ~[stagemonitor-configuration-0.87.5.jar:0.87.5]
        at org.stagemonitor.configuration.source.PropertyFileConfigurationSource.getProperties(PropertyFileConfigurationSource.java:65) ~[stagemonitor-configuration-0.87.5.jar:0.87.5]
        at org.stagemonitor.configuration.source.PropertyFileConfigurationSource.reload(PropertyFileConfigurationSource.java:40) ~[stagemonitor-configuration-0.87.5.jar:0.87.5]
        at org.stagemonitor.configuration.ConfigurationRegistry.reload(ConfigurationRegistry.java:320) [stagemonitor-configuration-0.87.5.jar:0.87.5]
        at org.stagemonitor.configuration.ConfigurationRegistry.reloadDynamicConfigurationOptions(ConfigurationRegistry.java:314) [stagemonitor-configuration-0.87.5.jar:0.87.5]
        at org.stagemonitor.configuration.ConfigurationRegistry$2.run(ConfigurationRegistry.java:267) [stagemonitor-configuration-0.87.5.jar:0.87.5]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_171]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_171]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
