### ISSUE TITLE
Application hangs on startup

### ISSUE THREAD

**Issue by felixbarny** [stagemonitor/stagemonitor#309]
In a specific case, the application can hang on startup:

Stack trace:

```
"async-grafana" #32 daemon prio=5 os_prio=0 tid=0x00007f5858acf000 nid=0x724c in Object.wait() [0x00007f584f7bd000]
   java.lang.Thread.State: RUNNABLE
        at org.stagemonitor.tracing.profiler.Profiler.<clinit>(Profiler.java:8)
        at org.jstage.shop.core.view.ViewModelDeprecationLogger.getIncludeTypeMatcher(ViewModelDeprecationLogger.java:32)
        at org.stagemonitor.core.instrument.StagemonitorByteBuddyTransformer.getTypeMatcher(StagemonitorByteBuddyTransformer.java:69)
        at org.stagemonitor.core.instrument.StagemonitorByteBuddyTransformer$1.matches(StagemonitorByteBuddyTransformer.java:53)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple.matches(AgentBuilder.java:8386)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple.resolve(AgentBuilder.java:8397)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Compound.resolve(AgentBuilder.java:8634)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.resolve(AgentBuilder.java:8953)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:8920)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:8883)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1300(AgentBuilder.java:8662)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:9237)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:9187)
        at java.security.AccessController.doPrivileged(Native Method)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:8809)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at org.apache.catalina.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:2944)
        - locked <0x00000007588000c8> (a org.apache.catalina.loader.WebappClassLoader)
        at org.apache.catalina.loader.WebappClassLoader.findClass(WebappClassLoader.java:1208)
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1688)
        - locked <0x00000007588000c8> (a org.apache.catalina.loader.WebappClassLoader)
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1569)
        at com.fasterxml.jackson.core.JsonFactory._createUTF8Generator(JsonFactory.java:1331)
        at com.fasterxml.jackson.core.JsonFactory.createGenerator(JsonFactory.java:1084)
        at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2964)
        at org.stagemonitor.core.util.JsonUtils.writeJsonToOutputStream(JsonUtils.java:67)
        at org.stagemonitor.core.util.HttpClient.writeRequestBody(HttpClient.java:149)
        at org.stagemonitor.core.util.HttpClient.access$000(HttpClient.java:25)
        at org.stagemonitor.core.util.HttpClient$2.withHttpURLConnection(HttpClient.java:56)
        at org.stagemonitor.core.util.HttpClient.send(HttpClient.java:103)
        at org.stagemonitor.core.util.HttpClient.send(HttpClient.java:76)
        at org.stagemonitor.core.util.HttpClient.sendAsJson(HttpClient.java:53)
        at org.stagemonitor.core.grafana.GrafanaClient$1.run(GrafanaClient.java:110)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

In this example, `stagemonitor.instrument.includes=org.jstage`. This application also defines a class derived from `StagemonitorByteBuddyTransformer`, org.jstage.shop.core.view.ViewModelDeprecationLogger. Stagemonitor gets initialized in a static code block:

```java
public final class Stagemonitor {
	[…]
	static {
		reset();
	}
	[…]
}
```

During this initialization, the `CorePlugin` gets initialized which spawns another thread (`async-grafana`) .

With commit 9ff2148, I changed the initialization order so that the `StagemonitorByteBuddyTransformer`s are initialized before the plug-ins are initialized (`StagemonitorPlugin#initializePlugin`).

So when the grafana thread a class was loaded, the method `org.jstage.shop.core.view.ViewModelDeprecationLogger.getIncludeTypeMatcher(ViewModelDeprecationLogger.java:32)` method was invoked by byte buddy. But this class in turn has also be transformed so that the `Profiler` is active in it. The Profiler then accesses the `Stagemonitor` class again:

```java
public final class Profiler {
	public static final long MIN_EXECUTION_TIME_NANOS = Stagemonitor.getPlugin(TracingPlugin.class).getMinExecutionTimeNanos();
	[…]
}
``` 

But the `Stagemonitor` class is not initialized yet as the static initializer is not fully executed yet. Thus the `async-grafana` thread is not able to access `Stagemonitor`, hence the application hangs.

I'm not fully certain why the startup thread is also blocked:

```
"localhost-startStop-1" #25 daemon prio=5 os_prio=0 tid=0x00007f5864009800 nid=0x723b waiting for monitor entry [0x00007f58bd66b000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at com.fasterxml.jackson.databind.node.JsonNodeFactory.nullNode(JsonNodeFactory.java:109)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:245)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:224)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeArray(JsonNodeDeserializer.java:270)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:227)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeArray(JsonNodeDeserializer.java:270)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:227)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:69)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3807)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2272)
        at org.stagemonitor.core.grafana.GrafanaClient.sendGrafanaDashboardAsync(GrafanaClient.java:76)
        at org.stagemonitor.core.CorePlugin.initializePlugin(CorePlugin.java:444)
        at org.stagemonitor.core.Stagemonitor.initializePlugin(Stagemonitor.java:238)
        at org.stagemonitor.core.Stagemonitor.initializePluginsInOrder(Stagemonitor.java:208)
        at org.stagemonitor.core.Stagemonitor.initializePlugins(Stagemonitor.java:194)
        at org.stagemonitor.core.Stagemonitor.start(Stagemonitor.java:106)
        at org.stagemonitor.core.Stagemonitor.doStartMonitoring(Stagemonitor.java:94)
        - locked <0x000000075880ee08> (a java.lang.Class for org.stagemonitor.core.Stagemonitor)
        at org.stagemonitor.core.Stagemonitor.startMonitoring(Stagemonitor.java:79)
        at org.stagemonitor.core.Stagemonitor.startMonitoring(Stagemonitor.java:84)
        - locked <0x000000075880ee08> (a java.lang.Class for org.stagemonitor.core.Stagemonitor)
        at org.stagemonitor.core.Stagemonitor.tryStartMonitoring(Stagemonitor.java:373)
        at org.stagemonitor.core.Stagemonitor.reset(Stagemonitor.java:356)
        at org.stagemonitor.core.Stagemonitor.<clinit>(Stagemonitor.java:50)
        at org.stagemonitor.web.servlet.ServletPlugin.<clinit>(ServletPlugin.java:66)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.apache.catalina.startup.WebappServiceLoader.loadServices(WebappServiceLoader.java:187)
        at org.apache.catalina.startup.WebappServiceLoader.load(WebappServiceLoader.java:152)
        at org.apache.catalina.startup.ContextConfig.processServletContainerInitializers(ContextConfig.java:1543)
        at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1265)
        at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:873)
        - locked <0x00000007588dfcf0> (a org.apache.catalina.startup.ContextConfig)
        at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:371)
        at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5355)
        - locked <0x00000007588273d0> (a org.apache.catalina.core.StandardContext)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        - locked <0x00000007588273d0> (a org.apache.catalina.core.StandardContext)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by felixbarny** [comment]
There are multiple problems here:
 * Initializing `Stagemonitor` in a static code block is dangerous
 * User-defined `StagemonitorByteBuddyTransfromer`s should not be profiled.
 * It's not clear when stagemonitor gets started. It could be initialized when...
   * the `Stagemonitor` class is first loaded and all required properties of the `MeasurementSession` (application, host, instance) are available.
   * the application name is resolved via the web application's `display-name`
   * the instance name is derived from `HttpServletRequest#getServerName` from the first incoming request

That's why it will only be possible to set the application and instance via configuration. To remain backwards compatibility, there will be default values for `stagemonitor.applicationName` (`My Application`) and `stagemonitor.instanceName` (`My Instance`). It's highly recommended to set them explicitly.
