### ISSUE TITLE
StageMonitor not starting

### ISSUE THREAD

**Issue by codefetcher** [stagemonitor/stagemonitor#326]
Whenever I'm trying to run my jar I'm getting an error :  
"WARN org.stagemonitor.core.instrument.AgentAttacher - Failed to perform runtime attachment of the stagemonitor agent. Make sure that you run your application with a JDK (not a JRE).To make stagemonitor work with a JRE, you have to add the following command line argument to the start of the JVM: -javaagent:/path/to/byte-buddy-agent-<version>.jar" I have passed the "-javaagent:" argument also to my code

**Comment by felixbarny** [comment]
Could you try starting your application with a JDK?

**Comment by codefetcher** [comment]
Hi, Yes i have tried still getting the same error...

**Comment by felixbarny** [comment]
Could you paste the [startup logs](https://github.com/stagemonitor/stagemonitor/wiki/Troubleshooting) and tell me how you are starting the application? Are you starting it via an IDE, maven, gradle or java -jar?

**Comment by codefetcher** [comment]
Sure...
Here are the startup logs,
16:51:57.213 [main] WARN org.stagemonitor.core.instrument.AgentAttacher - Failed to perform runtime attachment of the stagemonitor agent. Make sure that you run your application with a JDK (not a JRE).To make stagemonitor work with a JRE, you have to add the following command line argument to the start of the JVM: -javaagent:/path/to/byte-buddy-agent-<version>.jar
java.lang.IllegalStateException: No compatible attachment provider is not available
        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:347)
        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:332)
        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:300)
        at org.stagemonitor.core.instrument.AgentAttacher.initInstrumentation(AgentAttacher.java:109)
        at org.stagemonitor.core.instrument.AgentAttacher.performRuntimeAttachment(AgentAttacher.java:83)
        at org.stagemonitor.core.Stagemonitor.reset(Stagemonitor.java:359)
        at org.stagemonitor.core.Stagemonitor.reset(Stagemonitor.java:341)
        at org.stagemonitor.core.Stagemonitor.init(Stagemonitor.java:62)
        at com.veritas.service.Application.main(Application.java:15)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
16:51:57.255 [main] INFO org.stagemonitor.core.Stagemonitor - Measurement Session is initialized: [application=My Application] [instance=My Instance] [host=W3068180LBUCE]
16:51:57.277 [main] INFO org.stagemonitor.core.CorePlugin - Not sending metrics to InfluxDB (url=null, interval=60s)
16:51:57.283 [main] INFO org.stagemonitor.core.CorePlugin - Not sending metrics to Elasticsearch (url=[], interval=60s)
16:51:57.364 [main] INFO org.stagemonitor.tracing.TracingPlugin - No OpenTracing implementation found. Falling back to NoopTracer. This is fine if you just want to use stagemonitor for development, for example with the in-browser-widget. If you want to report your traces to Elasticsearch, add a dependency to stagemonitor-tracing-elasticsearch. If you want to report to Zipkin, add stagemonitor-tracing-zipkin.
16:51:57.427 [main] INFO org.stagemonitor.core.Stagemonitor - # stagemonitor status
16:51:57.429 [main] INFO org.stagemonitor.core.Stagemonitor - System information: Java 1.8.0_131 (Oracle Corporation) Windows 10 10.0
16:51:57.434 [main] INFO org.stagemonitor.core.Stagemonitor - FAIL - Agent attachment (Failed to perform runtime attachment of the stagemonitor agent. Make sure that you run your application with a JDK (not a JRE).To make stagemonitor work with a JRE, you have to add the following command line argument to the start of the JVM: -javaagent:/path/to/byte-buddy-agent-<version>.jar)
16:51:57.447 [main] INFO org.stagemonitor.core.Stagemonitor - OK   - CorePlugin (version 0.83.2)
16:51:57.465 [main] INFO org.stagemonitor.core.Stagemonitor - FAIL - Elasticsearch (Elasticsearch is not available)
16:51:57.473 [main] INFO org.stagemonitor.core.Stagemonitor - OK   - JdbcPlugin (version 0.83.2)
16:51:57.478 [main] INFO org.stagemonitor.core.Stagemonitor - OK   - JvmPlugin (version 0.83.2)
16:51:57.487 [main] INFO org.stagemonitor.core.Stagemonitor - OK   - ServletPlugin (version 0.83.2)
16:51:57.490 [main] INFO org.stagemonitor.core.Stagemonitor - OK   - SoapTracingPlugin (version 0.83.2)
16:51:57.499 [main] INFO org.stagemonitor.core.Stagemonitor - OK   - Startup
16:51:57.506 [main] INFO org.stagemonitor.core.Stagemonitor - OK   - TracingPlugin (version 0.83.2)
16:51:57.508 [main] INFO org.stagemonitor.core.Stagemonitor - # stagemonitor configuration, listing non-default values:
16:51:57.518 [main] WARN org.stagemonitor.core.Stagemonitor - stagemonitor has not been configured. Have a look at
16:51:57.521 [main] WARN org.stagemonitor.core.Stagemonitor - https://github.com/stagemonitor/stagemonitor/wiki/How-should-I-configure-stagemonitor%3F
16:51:57.531 [main] WARN org.stagemonitor.core.Stagemonitor - and
16:51:57.539 [main] WARN org.stagemonitor.core.Stagemonitor - https://github.com/stagemonitor/stagemonitor/wiki/Configuration-Options
16:51:57.543 [main] WARN org.stagemonitor.core.Stagemonitor - for further instructions

I'm running it through eclipse IDE and through command prompt as well. And at both places I'm getting same error

**Comment by felixbarny** [comment]
Could you show me a screenshot of your eclipse configuration? I want to make sure its really an JDK.

**Comment by codefetcher** [comment]
![eclipse](https://user-images.githubusercontent.com/14290680/30806378-300e8e80-a213-11e7-8c97-db472bc3e98c.png)

**Comment by felixbarny** [comment]
Ok, could you verify that in this is also configured in Run configuration > Main > Execution Environment?

**Comment by codefetcher** [comment]
Yes, It is..
Shall i send you the screenshot?

**Comment by felixbarny** [comment]
That's strange. Yes, if you want attach a screenshot. You said you also tried the `-javaagent` approach? Could you also send me a screenshot for that configuration? Which byte-buddy-agent version did you use?

**Comment by codefetcher** [comment]
![image](https://user-images.githubusercontent.com/14290680/30807090-0a4c7da8-a216-11e7-9b21-46c3932653c9.png)

**Comment by codefetcher** [comment]
For, -javaagent i have used buddy agent 0.5

![image](https://user-images.githubusercontent.com/14290680/30807237-a104ec44-a216-11e7-8c29-c3a89c16387f.png)

**Comment by felixbarny** [comment]
The correct version for stagemonitor 0.83.2 is byte buddy 1.6.13 (see [here](https://github.com/stagemonitor/stagemonitor/blob/0.83.2/build.gradle#L57). You can get it here: http://central.maven.org/maven2/net/bytebuddy/byte-buddy-agent/1.6.13/byte-buddy-agent-1.6.13.jar

**Comment by codefetcher** [comment]
Thank you but I'm getting the following error 

`C:\Users\mayank.gupta\git\apps-data-reciever\build\libs>java -jar DataReceiver-0.0.1-SNAPSHOT.jar -javaagent:/byte-buddy-agent-1.6.13.jar
10:10:54.093 [main] WARN org.stagemonitor.core.instrument.AgentAttacher - Failed to perform runtime attachment of the stagemonitor agent. Make sure that you run your application with a JDK (not a JRE).To make stagemonitor work with a JRE, you have to add the following command line argument to the start of the JVM: -javaagent:/path/to/byte-buddy-agent-<version>.jar
java.lang.IllegalStateException: No compatible attachment provider is not available
        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:347)
        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:332)
        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:300)
        at org.stagemonitor.core.instrument.AgentAttacher.initInstrumentation(AgentAttacher.java:109)
        at org.stagemonitor.core.instrument.AgentAttacher.performRuntimeAttachment(AgentAttacher.java:83)
        at org.stagemonitor.core.Stagemonitor.reset(Stagemonitor.java:359)
        at org.stagemonitor.core.Stagemonitor.reset(Stagemonitor.java:341)
        at org.stagemonitor.core.Stagemonitor.init(Stagemonitor.java:62)
        at com.veritas.service.Application.main(Application.java:15)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
10:10:54.146 [main] INFO org.stagemonitor.core.Stagemonitor - Measurement Session is initialized: [application=My Application] [instance=My Instance] [host=W3068180LBUCE]
10:10:54.220 [main] INFO org.stagemonitor.core.CorePlugin - Not sending metrics to InfluxDB (url=null, interval=60s)
10:10:54.226 [main] INFO org.stagemonitor.core.CorePlugin - Not sending metrics to Elasticsearch (url=[], interval=60s)
10:10:54.310 [main] INFO org.stagemonitor.tracing.TracingPlugin - No OpenTracing implementation found. Falling back to NoopTracer. This is fine if you just want to use stagemonitor for development, for example with the in-browser-widget. If you want to report your traces to Elasticsearch, add a dependency to stagemonitor-tracing-elasticsearch. If you want to report to Zipkin, add stagemonitor-tracing-zipkin.
10:10:54.378 [main] INFO org.stagemonitor.core.Stagemonitor - # stagemonitor status
10:10:54.381 [main] INFO org.stagemonitor.core.Stagemonitor - System information: Java 1.8.0_131 (Oracle Corporation) Windows 10 10.0
10:10:54.387 [main] INFO org.stagemonitor.core.Stagemonitor - FAIL - Agent attachment (Failed to perform runtime attachment of the stagemonitor agent. Make sure that you run your application with a JDK (not a JRE).To make stagemonitor work with a JRE, you have to add the following command line argument to the start of the JVM: -javaagent:/path/to/byte-buddy-agent-<version>.jar)
10:10:54.407 [main] INFO org.stagemonitor.core.Stagemonitor - OK   - CorePlugin (version 0.83.2)
10:10:54.424 [main] INFO org.stagemonitor.core.Stagemonitor - FAIL - Elasticsearch (Elasticsearch is not available)
10:10:54.432 [main] INFO org.stagemonitor.core.Stagemonitor - OK   - JdbcPlugin (version 0.83.2)
10:10:54.435 [main] INFO org.stagemonitor.core.Stagemonitor - OK   - JvmPlugin (version 0.83.2)
10:10:54.448 [main] INFO org.stagemonitor.core.Stagemonitor - OK   - ServletPlugin (version 0.83.2)
10:10:54.451 [main] INFO org.stagemonitor.core.Stagemonitor - OK   - SoapTracingPlugin (version 0.83.2)
10:10:54.463 [main] INFO org.stagemonitor.core.Stagemonitor - OK   - Startup
10:10:54.465 [main] INFO org.stagemonitor.core.Stagemonitor - OK   - TracingPlugin (version 0.83.2)
10:10:54.480 [main] INFO org.stagemonitor.core.Stagemonitor - # stagemonitor configuration, listing non-default values:
10:10:54.487 [main] WARN org.stagemonitor.core.Stagemonitor - stagemonitor has not been configured. Have a look at
10:10:54.493 [main] WARN org.stagemonitor.core.Stagemonitor - https://github.com/stagemonitor/stagemonitor/wiki/How-should-I-configure-stagemonitor%3F
10:10:54.509 [main] WARN org.stagemonitor.core.Stagemonitor - and
10:10:54.512 [main] WARN org.stagemonitor.core.Stagemonitor - https://github.com/stagemonitor/stagemonitor/wiki/Configuration-Options
10:10:54.528 [main] WARN org.stagemonitor.core.Stagemonitor - for further instructions

  .   ____          _            __ _ _`
And Later while hitting the url i get the following error

 `2017-09-26 10:11:37.682  INFO 13532 --- [nio-3000-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring FrameworkServlet 'dispatcherServlet'
2017-09-26 10:11:37.690  INFO 13532 --- [nio-3000-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization started
2017-09-26 10:11:37.725  INFO 13532 --- [nio-3000-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization completed in 27 ms
2017-09-26 10:11:37.755  WARN 13532 --- [nio-3000-exec-1] o.s.web.servlet.PageNotFound             : No mapping found for HTTP request with URI [/stagemonitor] in DispatcherServlet with name 'dispatcherServlet'
2017-09-26 10:11:37.810 ERROR 13532 --- [nio-3000-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] threw exception

javax.servlet.ServletException: Circular view path [error]: would dispatch back to the current handler URL [/error] again. Check your ViewResolver setup! (Hint: This may be the result of an unspecified view, due to default view name generation.)
        at org.springframework.web.servlet.view.InternalResourceView.prepareForRendering(InternalResourceView.java:205) ~[spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
        at org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:145) ~[spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
        at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303) ~[spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1286) ~[spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1041) ~[spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:984) ~[spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) ~[spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) ~[spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) ~[tomcat-embed-core-8.5.16.jar!/:8.5.16]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) ~[spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[tomcat-embed-core-8.5.16.jar!/:8.5.16]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-8.5.16.jar!/:8.5.16]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.16.jar!/:8.5.16]
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:469) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:392) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:311) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
        at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:395) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
        at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:254) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:177) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_131]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_131]`

**Comment by felixbarny** [comment]
The only thing I can then think of is that there is something wrong with your JDK installation.

I don't think the `javax.servlet.ServletException: Circular view path [error]` can be caused 
by stagemonitor. It seems to indicate that while handling an error, you application encounters another error and wants to dispatch to `/error` again.
