### ISSUE TITLE
dropwizard - browser widget?

### ISSUE THREAD

**Issue by qmnonic** [stagemonitor/stagemonitor#346]
Can't seem to get the browser widget working with dropwizard (1.1.1), java8 (1.8.0_77), byte-buddy (1.7.9).  Dropwizard is just hosting APIs on 8080, contextroot is /.  Admin is running on another port (8081) with contextroot /.  I'm calling StageMonitor.init(), and can see stagemonitor startup in the logs, i just can't figure out how to load the browser widget.

Neither of the following work:
http://localhost:8080/stagemonitor
http://localhost:8081/stagemonitor

I am clearly missing something - any help would be greatly appreciated.

**Comment by felixbarny** [comment]
Could you post the starup logs? Which embedded server are you using?

**Comment by qmnonic** [comment]
Dropwizard uses jetty.  I will grab logs and post them

Matt
(mobile)

**Comment by felixbarny** [comment]
See the installation Guide how to enable the stagemonitor enpoints on jetty: https://github.com/stagemonitor/stagemonitor/wiki/Step-1%3A-In-Browser-Widget#jetty

**Comment by qmnonic** [comment]
I saw the jetty guide, but found there was no `ServletPlugin().onStartup(...,...)` method as shown in the docs, but found `ServletPlugin.Initializer().onStartup(...)`, so am calling that.

**Code**: Added in the TestApplication.run method for the dropwizard app...
```
	@Override
	public void run(TestConfiguration config, Environment environment) throws Exception {
                // other stuff here...

		environment.lifecycle().addLifeCycleListener(new AbstractLifeCycle.AbstractLifeCycleListener() {
		    @Override
		    public void lifeCycleStarting(LifeCycle event) {
		        new ServletPlugin.Initializer().onStartup(environment.getApplicationContext().getServletContext());
		    }
		});
      }
```

**Logs** - end of logs, where the stagemonitor stuff happens.
```
INFO  [2017-11-08 17:27:24] o.s.t.soap.SoapHandlerTransformer - Adding SOAPHandlers [org.stagemonitor.tracing.soap.TracingServerSOAPHandler@c2af5f, org.stagemonitor.tracing.soap.TracingClientSOAPHandler@3ffc1e80] 
 DEBUG [2017-11-08 17:27:25] o.s.c.i.StagemonitorByteBuddyTransformer - Error while creating advice. This usually means that an optional type is not present so this is nothing wo worry about. Error message: org/springframework/http/client/support/InterceptingHttpAccessor 
 INFO  [2017-11-08 17:27:25] o.s.j.ConnectionMonitoringTransformer - TRANSFORM DataSource org.apache.tomcat.jdbc.pool.DataSourceProxy (DefaultConnectionMonitoringTransformer) 
 INFO  [2017-11-08 17:27:25] org.stagemonitor.core.Stagemonitor - Measurement Session is initialized: [application=services] [instance=local] [host=localhost] 
 INFO  [2017-11-08 17:27:26] org.stagemonitor.core.CorePlugin - Not sending metrics to InfluxDB (url=null, interval=60s) 
 INFO  [2017-11-08 17:27:26] org.stagemonitor.core.CorePlugin - Not sending metrics to Elasticsearch (url=[], interval=60s) 
 INFO  [2017-11-08 17:27:26] o.stagemonitor.tracing.TracingPlugin - No OpenTracing implementation found. Falling back to DefaultTracerImpl. This is fine if you just want to use stagemonitor for development, for example with the in-browser-widget. If you want to report your traces to Elasticsearch, add a dependency to stagemonitor-tracing-elasticsearch. If you want to report to Zipkin, add stagemonitor-tracing-zipkin. 
 INFO  [2017-11-08 17:27:27] o.s.alerting.AlertingPlugin - Using ConcurrentMapIncidentRepository for storing incidents. 
 INFO  [2017-11-08 17:27:27] org.stagemonitor.core.Stagemonitor - # stagemonitor status 
 INFO  [2017-11-08 17:27:27] org.stagemonitor.core.Stagemonitor - System information: Java 1.8.0_77 (Oracle Corporation) Mac OS X 10.12.6 
 INFO  [2017-11-08 17:27:27] org.stagemonitor.core.Stagemonitor - OK   - Agent attachment  
 INFO  [2017-11-08 17:27:27] org.stagemonitor.core.Stagemonitor - OK   - AlertingPlugin (version 0.85.0) 
 INFO  [2017-11-08 17:27:27] org.stagemonitor.core.Stagemonitor - OK   - CorePlugin (version 0.85.0) 
 INFO  [2017-11-08 17:27:27] org.stagemonitor.core.Stagemonitor - FAIL - Elasticsearch (Elasticsearch is not available) 
 INFO  [2017-11-08 17:27:27] org.stagemonitor.core.Stagemonitor - OK   - JdbcPlugin (version 0.85.0) 
 INFO  [2017-11-08 17:27:27] org.stagemonitor.core.Stagemonitor - OK   - JvmPlugin (version 0.85.0) 
 INFO  [2017-11-08 17:27:27] org.stagemonitor.core.Stagemonitor - OK   - OsPlugin (version 0.85.0) 
 INFO  [2017-11-08 17:27:27] org.stagemonitor.core.Stagemonitor - OK   - ServletPlugin (version 0.85.0) 
 INFO  [2017-11-08 17:27:27] org.stagemonitor.core.Stagemonitor - OK   - SoapTracingPlugin (version 0.85.0) 
 INFO  [2017-11-08 17:27:27] org.stagemonitor.core.Stagemonitor - OK   - Startup  
 INFO  [2017-11-08 17:27:27] org.stagemonitor.core.Stagemonitor - OK   - TracingPlugin (version 0.85.0) 
 INFO  [2017-11-08 17:27:27] org.stagemonitor.core.Stagemonitor - # stagemonitor configuration, listing non-default values: 
 INFO  [2017-11-08 17:27:27] org.stagemonitor.core.Stagemonitor - stagemonitor.applicationName: services (source: stagemonitor.properties) 
 INFO  [2017-11-08 17:27:27] org.stagemonitor.core.Stagemonitor - stagemonitor.instanceName: local (source: stagemonitor.properties) 
 INFO  [2017-11-08 17:27:27] org.stagemonitor.core.Stagemonitor - stagemonitor.hostName: localhost (source: stagemonitor.properties) 
 INFO  [2017-11-08 17:27:27] org.stagemonitor.core.Stagemonitor - stagemonitor.instrument.include: io.innerspace (source: stagemonitor.properties) 
 INFO  [2017-11-08 17:27:27] o.s.w.s.c.ConfigurationServlet - Registering configuration Endpoint /stagemonitor/configuration. You can dynamically change the configuration by issuing a POST request to /stagemonitor/configuration?key=stagemonitor.config.key&value=configValue&stagemonitor.password=password. If the password is not set, dynamically changing the configuration is not available. The password can be omitted if set to an empty string. 
 ERROR [2017-11-08 17:27:27] io.dropwizard.cli.ServerCommand - Unable to start server, shutting down 
java.lang.IllegalStateException: null
	at org.eclipse.jetty.servlet.ServletContextHandler$Context.addServlet(ServletContextHandler.java:1262)
	at org.stagemonitor.web.servlet.ServletPlugin$Initializer.onStartup(ServletPlugin.java:468)
	at com.innerspace.services.InnerSpaceApplication$4.lifeCycleStarting(InnerSpaceApplication.java:176)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.setStarting(AbstractLifeCycle.java:188)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:67)
	at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
	at io.dropwizard.cli.Cli.run(Cli.java:74)
	at io.dropwizard.Application.run(Application.java:89)
	at com.innerspace.services.InnerSpaceApplication.main(InnerSpaceApplication.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
	at java.lang.Thread.run(Thread.java:745)
null
```

**Comment by qmnonic** [comment]
Clean dropwizard example app that I added stagewizard to for your testing - https://github.com/qmnonic/dropwizard/tree/master/dropwizard-example .

See the single commit that adds dependencies and the `ServletPlugin.Initializer.onStartup` call.

You'll see the error in the package phase, which attempts to start dropwizard for tests:
`mvn -Denforcer.skip=true package`

**Comment by qmnonic** [comment]
See solution in dropwizard ticket #2209 - https://github.com/dropwizard/dropwizard/issues/2209

**Comment by felixbarny** [comment]
Thx a lot mate. I'll update the documentation.
