### ISSUE TITLE
ServletPlugin.clientSpanExtensions is null

### ISSUE THREAD

**Issue by felixoldenburg** [stagemonitor/stagemonitor#349]
Hi,
in the 0.0.85 release when disabling Stagemonitor via Elasticsearch configuration, there's a NPE preventing the Spring Web Application Context of our app to start.

```
Caused by: java.lang.NullPointerException
	at org.stagemonitor.web.servlet.eum.ClientSpanJavaScriptServlet.concatenateJavaScript(ClientSpanJavaScriptServlet.java:53)
	at org.stagemonitor.web.servlet.eum.ClientSpanJavaScriptServlet.rebuildJavaScriptAndEtag(ClientSpanJavaScriptServlet.java:42)
	at org.stagemonitor.web.servlet.eum.ClientSpanJavaScriptServlet.<init>(ClientSpanJavaScriptServlet.java:37)
	at org.stagemonitor.web.servlet.eum.ClientSpanJavaScriptServlet.<init>(ClientSpanJavaScriptServlet.java:32)
	at org.stagemonitor.web.servlet.ServletPlugin$Initializer.onStartup(ServletPlugin.java:474)
	at org.stagemonitor.web.servlet.initializer.ServletContainerInitializerUtil.registerStagemonitorServletContainerInitializers(ServletContainerInitializerUtil.java:19)
	at org.stagemonitor.web.servlet.initializer.MainStagemonitorServletContainerInitializer.onStartup(MainStagemonitorServletContainerInitializer.java:12)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5303)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
```

The newly introduced field clientSpanExtensions of ServletPlugin doesn't seem to be initialized.

If any information are missing, let me know.

Best,
Felix Oldenburg.

**Comment by felixbarny** [comment]
thx a lot for reporting! Initializing the list with Collections.emptyList() should fix the issue. Do you want to provide a pull request?
