### ISSUE TITLE
Stagemonitor change method return type

### ISSUE THREAD

**Issue by TimYi** [stagemonitor/stagemonitor#355]
I use some tricks in my entity, which will be query out by mybatis.
```
@JsonIgnore
public void setContent(String content) {
	if (content == null || content.isEmpty()) {
		return;
	}
	DocumentBody body = SnakeJsonSerializer.deSerialize(content, DocumentBody.class);
	setParagraphs(body.getParagraphs());
	setParagraphAddresses(body.getParagraphAddresses());
}
```
Mybatis set the content property with the the content field(a json string) of ResultSet.
Without slate, it works fine.
After add stagemonitor 0.84.1 as a dependency, mybatis throws error can ```not convert string to List```.
I think stagemonitor must have changed the parameter type from string to List of this method, when mybatis tries to reflect it.

**Comment by felixbarny** [comment]
Could you paste the whole stack trace?

**Comment by TimYi** [comment]
Sure
```
nested exception is org.apache.ibatis.reflection.ReflectionException: Could not set property 'operationsJson' of 'class com.jiurong.mnote.transition.ot.core.CompondMnoteOperation' with value '[{"type":"MP","valid":true,"executable":true,"paragraph_id":"b089a590cabd11e7a3991d5efc64a6d0","paragraph":{"paragraph_type":"TEXT","id":"b089a590cabd11e7a3991d5efc64a6d0","content":[{"element_type":"TEXT","text":"qewrewr","element_type":"TEXT","empty":false}],"paragraph_type":"TEXT"},"old_paragraph":{"paragraph_type":"TEXT","id":"b089a590cabd11e7a3991d5efc64a6d0","content":[],"paragraph_type":"TEXT"},"version":0}]' Cause: java.lang.IncompatibleClassChangeError: Found class com.jiurong.mnote.transition.ot.core.MnoteOperation, but interface was expected
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.reflection.ReflectionException: Could not set property 'operationsJson' of 'class com.jiurong.mnote.transition.ot.core.CompondMnoteOperation' with value '[{"type":"MP","valid":true,"executable":true,"paragraph_id":"b089a590cabd11e7a3991d5efc64a6d0","paragraph":{"paragraph_type":"TEXT","id":"b089a590cabd11e7a3991d5efc64a6d0","content":[{"element_type":"TEXT","text":"qewrewr","element_type":"TEXT","empty":false}],"paragraph_type":"TEXT"},"old_paragraph":{"paragraph_type":"TEXT","id":"b089a590cabd11e7a3991d5efc64a6d0","content":[],"paragraph_type":"TEXT"},"version":0}]' Cause: java.lang.IncompatibleClassChangeError: Found class com.jiurong.mnote.transition.ot.core.MnoteOperation, but interface was expected
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77) ~[mybatis-spring-1.3.1.jar:1.3.1]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446) ~[mybatis-spring-1.3.1.jar:1.3.1]
	at com.sun.proxy.$Proxy137.selectList(Unknown Source) ~[?:?]
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230) ~[mybatis-spring-1.3.1.jar:1.3.1]
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:137) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:75) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59) ~[mybatis-3.4.5.jar:3.4.5]
	at com.sun.proxy.$Proxy150.findOperations(Unknown Source) ~[?:?]
	at com.jiurong.mnote.transition.ot.repository.OperationRepositoryImpl.getOperationsAfter(OperationRepositoryImpl.java:25) ~[jiurong-mnote-transition-0.4.2-SNAPSHOT.jar:0.4.2-SNAPSHOT]
	at com.jiurong.mnote.transition.ot.repository.OperationRepositoryImpl$$FastClassBySpringCGLIB$$aa5f7f7b.invoke(<generated>) ~[jiurong-mnote-transition-0.4.2-SNAPSHOT.jar:0.4.2-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720) ~[spring-aop-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spring-tx-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281) ~[spring-tx-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655) ~[spring-aop-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at com.jiurong.mnote.transition.ot.repository.OperationRepositoryImpl$$EnhancerBySpringCGLIB$$626f7cbc.getOperationsAfter(<generated>) ~[jiurong-mnote-transition-0.4.2-SNAPSHOT.jar:0.4.2-SNAPSHOT]
	at com.jiurong.mnote.transition.document.service.DocumentServiceImpl.generateVersionDocument(DocumentServiceImpl.java:228) ~[jiurong-mnote-transition-0.4.2-SNAPSHOT.jar:0.4.2-SNAPSHOT]
	at com.jiurong.mnote.transition.document.service.DocumentServiceImpl$$FastClassBySpringCGLIB$$571aec9.invoke(<generated>) ~[jiurong-mnote-transition-0.4.2-SNAPSHOT.jar:0.4.2-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720) ~[spring-aop-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spring-tx-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281) ~[spring-tx-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655) ~[spring-aop-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at com.jiurong.mnote.transition.document.service.DocumentServiceImpl$$EnhancerBySpringCGLIB$$765f0b66.generateVersionDocument(<generated>) ~[jiurong-mnote-transition-0.4.2-SNAPSHOT.jar:0.4.2-SNAPSHOT]
	at com.jiurong.mnote.transition.history.service.BaseHistoryService.editHistory(BaseHistoryService.java:222) ~[jiurong-mnote-transition-0.4.2-SNAPSHOT.jar:0.4.2-SNAPSHOT]
	at com.jiurong.mnote.transition.history.service.BaseHistoryService.processEvent(BaseHistoryService.java:142) ~[jiurong-mnote-transition-0.4.2-SNAPSHOT.jar:0.4.2-SNAPSHOT]
	at com.jiurong.mnote.transition.history.service.BaseHistoryService.processEvents(BaseHistoryService.java:112) [jiurong-mnote-transition-0.4.2-SNAPSHOT.jar:0.4.2-SNAPSHOT]
	at com.jiurong.mnote.transition.history.service.BaseHistoryService$$FastClassBySpringCGLIB$$7ea6c8a0.invoke(<generated>) [jiurong-mnote-transition-0.4.2-SNAPSHOT.jar:0.4.2-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720) [spring-aop-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) [spring-tx-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281) [spring-tx-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) [spring-tx-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655) [spring-aop-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at com.jiurong.mfront.mnote.history.HistoryServiceImpl$$EnhancerBySpringCGLIB$$68aa6192.processEvents(<generated>) [jiurong-mnote-mfront-0.4.2-SNAPSHOT.jar:0.4.2-SNAPSHOT]
	at com.jiurong.task.MnoteTask.processHistoryEvents(MnoteTask.java:75) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor193.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: org.apache.ibatis.reflection.ReflectionException: Could not set property 'operationsJson' of 'class com.jiurong.mnote.transition.ot.core.CompondMnoteOperation' with value '[{"type":"MP","valid":true,"executable":true,"paragraph_id":"b089a590cabd11e7a3991d5efc64a6d0","paragraph":{"paragraph_type":"TEXT","id":"b089a590cabd11e7a3991d5efc64a6d0","content":[{"element_type":"TEXT","text":"qewrewr","element_type":"TEXT","empty":false}],"paragraph_type":"TEXT"},"old_paragraph":{"paragraph_type":"TEXT","id":"b089a590cabd11e7a3991d5efc64a6d0","content":[],"paragraph_type":"TEXT"},"version":0}]' Cause: java.lang.IncompatibleClassChangeError: Found class com.jiurong.mnote.transition.ot.core.MnoteOperation, but interface was expected
	at org.apache.ibatis.reflection.wrapper.BeanWrapper.setBeanProperty(BeanWrapper.java:185) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.reflection.wrapper.BeanWrapper.set(BeanWrapper.java:59) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.reflection.MetaObject.setValue(MetaObject.java:140) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.applyPropertyMappings(DefaultResultSetHandler.java:450) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.getRowValue(DefaultResultSetHandler.java:399) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleRowValuesForSimpleResultMap(DefaultResultSetHandler.java:351) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleRowValues(DefaultResultSetHandler.java:326) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSet(DefaultResultSetHandler.java:299) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSets(DefaultResultSetHandler.java:192) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:64) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.executor.ReuseExecutor.doQuery(ReuseExecutor.java:60) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:136) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141) ~[mybatis-3.4.5.jar:3.4.5]
	at sun.reflect.GeneratedMethodAccessor169.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433) ~[mybatis-spring-1.3.1.jar:1.3.1]
	... 54 more
Caused by: java.lang.IncompatibleClassChangeError: Found class com.jiurong.mnote.transition.ot.core.MnoteOperation, but interface was expected
	at com.jiurong.mnote.transition.ot.core.MnoteOperation$Access4JacksonDeserializere3f3a29d.longSetter(com/jiurong/mnote/transition/ot/core/MnoteOperation$Access4JacksonDeserializer.java) ~[?:0.4.2-SNAPSHOT]
	at com.fasterxml.jackson.module.afterburner.deser.SettableLongMethodProperty.deserializeAndSet(SettableLongMethodProperty.java:42) ~[jackson-module-afterburner-2.9.0.jar:2.9.0]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:251) ~[jackson-databind-2.9.0.jar:2.9.0]
	at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:155) ~[jackson-module-afterburner-2.9.0.jar:2.9.0]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:285) ~[jackson-databind-2.9.0.jar:2.9.0]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244) ~[jackson-databind-2.9.0.jar:2.9.0]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27) ~[jackson-databind-2.9.0.jar:2.9.0]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001) ~[jackson-databind-2.9.0.jar:2.9.0]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3030) ~[jackson-databind-2.9.0.jar:2.9.0]
	at com.jiurong.foundation.json.SnakeJsonSerializer.deSerialize(SnakeJsonSerializer.java:71) ~[jiurong-foundation-0.4.2-SNAPSHOT.jar:0.4.2-SNAPSHOT]
	at com.jiurong.mnote.transition.ot.core.CompondMnoteOperation.setOperationsJson(CompondMnoteOperation.java:129) ~[jiurong-mnote-transition-0.4.2-SNAPSHOT.jar:0.4.2-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
	at org.apache.ibatis.reflection.invoker.MethodInvoker.invoke(MethodInvoker.java:41) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.reflection.wrapper.BeanWrapper.setBeanProperty(BeanWrapper.java:180) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.reflection.wrapper.BeanWrapper.set(BeanWrapper.java:59) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.reflection.MetaObject.setValue(MetaObject.java:140) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.applyPropertyMappings(DefaultResultSetHandler.java:450) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.getRowValue(DefaultResultSetHandler.java:399) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleRowValuesForSimpleResultMap(DefaultResultSetHandler.java:351) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleRowValues(DefaultResultSetHandler.java:326) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSet(DefaultResultSetHandler.java:299) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSets(DefaultResultSetHandler.java:192) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:64) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.executor.ReuseExecutor.doQuery(ReuseExecutor.java:60) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:136) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141) ~[mybatis-3.4.5.jar:3.4.5]
	at sun.reflect.GeneratedMethodAccessor169.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433) ~[mybatis-spring-1.3.1.jar:1.3.1]
	... 54 more
```

**Comment by TimYi** [comment]
I look into this error, and find I misunderstand the mistake, something of stagemonitor affect Jackson's behavior.

**Comment by TimYi** [comment]
I think this may be the issue:
```
JavaType type = TypeFactory.defaultInstance().constructCollectionType(ArrayList.class,
	MnoteOperation.class);
operations = SnakeJsonSerializer.deSerialize(json, type);
```
I tell jackson element type of list is MnoteOperation. Jackson try to build a MnoteOperation, but stagemonitor change it to some other interface, so Jackson throws an error?

**Comment by TimYi** [comment]
I remove all jars whose name contains 'stagemonitor'. But still have the same error.
Until I remove all stagemonitor dependency from pom, and redeploy, the error disappear.
I guess it's byte-buddy conflict whit jackson JavaType deserialize mechanism.

**Comment by felixbarny** [comment]
I think its bc of jackson afterburner. Could you try to remove that dependency?

**Comment by felixbarny** [comment]
Are you maybe calling `com.fasterxml.jackson.databind.ObjectMapper#findModules()`? If yes, the Afterburner module will be automatically picked up if it's on the class path.

**Comment by TimYi** [comment]
@felixbarny Yes, ```com.fasterxml.jackson.databind.ObjectMapper#findAndRegisterModules();``` called.

**Comment by felixbarny** [comment]
jackson-afterburner is a transitive dependency of stagemonitor-core. It also appears in the stack trace you posted:

```
at com.fasterxml.jackson.module.afterburner.deser.SettableLongMethodProperty.deserializeAndSet(SettableLongMethodProperty.java:42) ~[jackson-module-afterburner-2.9.0.jar:2.9.0]
```

So your best bet is to [exclude](https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html#Dependency_Exclusions) jackson-module-afterburner in pom.xml when declaring the dependency on stagemonitor.
