### ISSUE TITLE
Some parts of Grafana's request metrics dashboard seem broken

### ISSUE THREAD

**Issue by yacota** [stagemonitor/stagemonitor#371]
After upgrading to stagemontor-0.87.2, in order to be able to use ES6, we've seen that some parts of the Grafana's request metrics dashboard seem empty/broken.

The error detailed message is the following

    {
    "root_cause": [
        {
            "type": "array_index_out_of_bounds_exception",
            "reason": "-1"
        }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
        {
            "shard": 0,
            "index": "stagemonitor-metrics-2018.01.30",
            "node": "2v_moLjUTKGKBIC3RAs-iQ",
            "reason": {
                "type": "array_index_out_of_bounds_exception",
                "reason": "-1"
            }
        }
    ]
}

![stagemonitor-grafana](https://user-images.githubusercontent.com/2678582/35592958-d72db5ce-060e-11e8-9a9f-33850b2541ff.png)

**Comment by yacota** [comment]
@trampi don't you have this problem in your prod env ?

**Comment by cirk0** [comment]
same issue with 0.87.11 with ES 5.6.8

**Comment by cirk0** [comment]
Here is an example of a related exception in Elasticsearch logs.

```
[2018-06-26T16:07:15,122][DEBUG][o.e.a.s.TransportSearchAction] [xwUlEaR] [stagemonitor-metrics-2018.06.26][0], node[xwUlEaRuSG2nOMGcv1abOg], [P], s[STARTED], a[id=cDEhL77fSs2_fmjQTZrotg]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[stagemonitor-metrics-2018.06.26], indicesOptions=IndicesOptions[id=39, ignore_unavailable=true, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_alisases_to_multiple_indices=true, forbid_closed_indices=true], types=[], routing='null', preference='null', requestCache=null, scroll=null, maxConcurrentShardRequests=5, batchedReduceSize=512, preFilterShardSize=64, source={
  "size" : 0,
  "query" : {
    "bool" : {
      "filter" : [
        {
          "range" : {
            "@timestamp" : {
              "from" : "1530007634794",
              "to" : "1530029234794",
              "include_lower" : true,
              "include_upper" : true,
              "format" : "epoch_millis",
              "boost" : 1.0
            }
          }
        },
        {
          "query_string" : {
            "query" : "name: external_requests_rate AND !operation_name: All AND application: Web\\-Services AND host: (\"ip\\-172\\-30\\-1\\-143.eu\\-west\\-1.compute.internal\" OR \"ip\\-172\\-30\\-1\\-152.eu\\-west\\-1.compute.internal\" OR \"ip\\-172\\-30\\-1\\-17.eu\\-west\\-1.compute.internal\" OR \"ip\\-172\\-30\\-1\\-174.eu\\-west\\-1.compute.internal\" OR \"ip\\-172\\-30\\-1\\-28.eu\\-west\\-1.compute.internal\" OR \"ip\\-172\\-30\\-1\\-31.eu\\-west\\-1.compute.internal\" OR \"ip\\-172\\-30\\-1\\-73.eu\\-west\\-1.compute.internal\") AND instance: (\"alpha\" OR \"beta\")",
            "fields" : [ ],
            "use_dis_max" : true,
            "tie_breaker" : 0.0,
            "default_operator" : "or",
            "auto_generate_phrase_queries" : false,
            "max_determinized_states" : 10000,
            "enable_position_increments" : true,
            "fuzziness" : "AUTO",
            "fuzzy_prefix_length" : 0,
            "fuzzy_max_expansions" : 50,
            "phrase_slop" : 0,
            "analyze_wildcard" : true,
            "escape" : false,
            "split_on_whitespace" : true,
            "boost" : 1.0
          }
        }
      ],
      "disable_coord" : false,
      "adjust_pure_negative" : true,
      "boost" : 1.0
    }
  },
  "aggregations" : {
    "3" : {
      "terms" : {
        "field" : "operation_name",
        "size" : 5,
        "min_doc_count" : 0,
        "shard_min_doc_count" : 0,
        "show_term_doc_count_error" : false,
        "order" : [
          {
            "1" : "desc"
          },
          {
            "_term" : "asc"
          }
        ]
      },
      "aggregations" : {
        "1" : {
          "avg" : {
            "field" : "m1_rate"
          }
        },
        "2" : {
          "date_histogram" : {
            "field" : "@timestamp",
            "format" : "epoch_millis",
            "interval" : "2m",
            "offset" : 0,
            "order" : {
              "_key" : "asc"
            },
            "keyed" : false,
            "min_doc_count" : 0,
            "extended_bounds" : {
              "min" : "1530007634794",
              "max" : "1530029234794"
            }
          },
          "aggregations" : {
            "1" : {
              "avg" : {
                "field" : "m1_rate"
              }
            }
          }
        }
      }
    }
  }
}}]
org.elasticsearch.transport.RemoteTransportException: [xwUlEaR][local[1]][indices:data/read/search[phase/query]]
Caused by: java.lang.ArrayIndexOutOfBoundsException
[2018-06-26T16:07:15,122][DEBUG][o.e.a.s.TransportSearchAction] [xwUlEaR] All shards failed for phase: [query]
org.elasticsearch.ElasticsearchException$1: null
	at org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:618) ~[elasticsearch-5.6.8.jar:5.6.8]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:126) ~[elasticsearch-5.6.8.jar:5.6.8]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:241) ~[elasticsearch-5.6.8.jar:5.6.8]
	at org.elasticsearch.action.search.InitialSearchPhase.onShardFailure(InitialSearchPhase.java:107) ~[elasticsearch-5.6.8.jar:5.6.8]
	at org.elasticsearch.action.search.InitialSearchPhase.access$100(InitialSearchPhase.java:49) ~[elasticsearch-5.6.8.jar:5.6.8]
	at org.elasticsearch.action.search.InitialSearchPhase$2.lambda$onFailure$1(InitialSearchPhase.java:217) ~[elasticsearch-5.6.8.jar:5.6.8]
	at org.elasticsearch.action.search.InitialSearchPhase.maybeFork(InitialSearchPhase.java:171) [elasticsearch-5.6.8.jar:5.6.8]
	at org.elasticsearch.action.search.InitialSearchPhase.access$000(InitialSearchPhase.java:49) [elasticsearch-5.6.8.jar:5.6.8]
	at org.elasticsearch.action.search.InitialSearchPhase$2.onFailure(InitialSearchPhase.java:217) [elasticsearch-5.6.8.jar:5.6.8]
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:51) [elasticsearch-5.6.8.jar:5.6.8]
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1077) [elasticsearch-5.6.8.jar:5.6.8]
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1181) [elasticsearch-5.6.8.jar:5.6.8]
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1159) [elasticsearch-5.6.8.jar:5.6.8]
	at org.elasticsearch.transport.TransportService$7.onFailure(TransportService.java:665) [elasticsearch-5.6.8.jar:5.6.8]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.onFailure(ThreadContext.java:659) [elasticsearch-5.6.8.jar:5.6.8]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39) [elasticsearch-5.6.8.jar:5.6.8]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.ArrayIndexOutOfBoundsException
```

**Comment by jpfourny** [comment]
I hit the same issue with PetClinic app against stagemonitor-docker-compose (both built today). In "Request Metrics" dashboard, the "Response Time" and "Throughput" panels are fine, but all the rest hit the ArrayIndexOutOfBounds.

**Comment by jpfourny** [comment]
I believe the problem is that the dashboards were authored in an older version of Grafana (probably 2.x). I imported them into Grafana 4 and manually fixed the issues (there were a few things). I also did an upgrade to Grafana 5 (again, the specs completely changed and stagemonitor code needs to be updated to compensate).

**Comment by cdalexndr** [comment]
Same issue with Stagemonitor 0.88.9, Grafana v6.2.5, Elasticsearch-6.8.1
