### ISSUE TITLE
Nullpointer exception when running in docker container

### ISSUE THREAD

**Issue by rjcrystal** [stagemonitor/stagemonitor#378]
i am trying to run a basic java application (non-web) inside a docker container which has stagemonitor for sending metrics to influxdb, but it fails during init with null pointer exception. i have defined application name, hostname, instance name, influxdb url, reporting interval.

i am getting following exception on init()
```
Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException at org.stagemonitor.core.Stagemonitor.init(Stagemonitor.java:61) at com.indiabizforsale.email.EmailServiceApplication.main(EmailServiceApplication.java:15) Caused by: java.lang.NullPointerException at org.stagemonitor.core.Stagemonitor.reset(Stagemonitor.java:307) at org.stagemonitor.core.Stagemonitor.reset(Stagemonitor.java:292) at org.stagemonitor.core.Stagemonitor.init(Stagemonitor.java:58) 

java.lang.NullPointerException: null at org.stagemonitor.core.StagemonitorCoreConfigurationSourceInitializer.onConfigurationInitialized(StagemonitorCoreConfigurationSourceInitializer.java:45) at org.stagemonitor.core.Stagemonitor.reloadPluginsAndConfiguration(Stagemonitor.java:341) at org.stagemonitor.core.Stagemonitor.<clinit>(Stagemonitor.java:49) at com.indiabizforsale.email.EmailServiceApplication.main(EmailServiceApplication.java:15)
```
Configuration file contents 

stagemonitor.applicationName=Email Service
stagemonitor.instrument.include=com.indiabizforsale.email
stagemonitor.active = true
stagemonitor.reporting.interval.influxdb = 2
stagemonitor.reporting.influxdb.db = ibfs_metrics
stagemonitor.profiler.active = false
stagemonitor.web.widget.enabled = false
stagemonitor.instanceName=email-service-pod

stagemonitor.reporting.influxdb.url is defined in environment. 

Running inside a docker container in google kubernetes engine

**Comment by 75devanshsharma** [comment]
Remove stagemonitor-tracing dependency from build file , if using.

**Comment by liebhaeuser** [comment]
Did you find the problem with this?
