### ISSUE TITLE
My application get an error when start after adding the dependency for elasticsearch

### ISSUE THREAD

**Issue by rainishjj** [stagemonitor/stagemonitor#389]
My application is based on spring boot 1.4+. I want to integrate stagemonitor with elasticsearch. As the issue #388, the jar jaeger version 0.22.0 has error, So I use 0.24.0 to replace it. every thing is ok when I start my application, I get the error: 
java.lang.NoSuchMethodError: io.opentracing.Tracer$SpanBuilder.startActive()Lio/opentracing/Scope;
	at org.stagemonitor.web.servlet.MonitoredHttpRequest.createScope(MonitoredHttpRequest.java:99)
	at org.stagemonitor.tracing.RequestMonitor.monitorStart(RequestMonitor.java:35)
	at org.stagemonitor.tracing.RequestMonitor.monitor(RequestMonitor.java:58)
	at org.stagemonitor.web.servlet.filter.HttpRequestMonitorFilter.monitorRequest(HttpRequestMonitorFilter.java:145)
	at org.stagemonitor.web.servlet.filter.HttpRequestMonitorFilter.doMonitor(HttpRequestMonitorFilter.java:107)
	at org.stagemonitor.web.servlet.filter.HttpRequestMonitorFilter.doFilterInternal(HttpRequestMonitorFilter.java:86)
	at org.stagemonitor.web.servlet.filter.AbstractExclusionFilter.doFilter(AbstractExclusionFilter.java:65)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331).

Here is my start log:
16:53:20.015 [main] WARN org.stagemonitor.configuration.ConfigurationOption - Error in stagemonitor.properties: no protocol: 192.168.20.84:9200 Default value '' for 'stagemonitor.reporting.elasticsearch.url' will be applied.
16:53:20.018 [main] WARN org.stagemonitor.configuration.ConfigurationOption - Error in stagemonitor.properties: no protocol: 192.168.20.84:9200 Default value '' for 'stagemonitor.reporting.elasticsearch.url' will be applied.
16:53:20.214 [main] INFO org.stagemonitor.tracing.soap.SoapHandlerTransformer - Adding SOAPHandlers [org.stagemonitor.tracing.soap.TracingServerSOAPHandler@34a875b3, org.stagemonitor.tracing.soap.TracingClientSOAPHandler@4748a0f9]
16:53:20.526 [main] INFO org.stagemonitor.core.Stagemonitor - Measurement Session is initialized: [application=CAAS WEB] [instance=dev] [host=DESKTOP-HQR11QV]
16:53:20.540 [main] INFO org.stagemonitor.core.CorePlugin - Not sending metrics to InfluxDB (url=null, interval=60s)
16:53:20.616 [main] INFO org.stagemonitor.web.servlet.ServletPlugin - Initializing ClientSpanExtensions [org.stagemonitor.web.servlet.eum.WeaselClientSpanExtension@71652c98]
16:53:20.657 [main] INFO org.stagemonitor.alerting.AlertingPlugin - Using ConcurrentMapIncidentRepository for storing incidents.
16:53:20.666 [main] INFO org.stagemonitor.core.Stagemonitor - # stagemonitor status
16:53:20.666 [main] INFO org.stagemonitor.core.Stagemonitor - System information: Java 1.8.0_144 (Oracle Corporation) Windows 10 10.0
16:53:20.668 [main] INFO org.stagemonitor.core.Stagemonitor - OK   - Agent attachment 
16:53:20.668 [main] INFO org.stagemonitor.core.Stagemonitor - OK   - AlertingPlugin (version 0.88.0)
16:53:20.668 [main] INFO org.stagemonitor.core.Stagemonitor - OK   - CorePlugin (version 0.88.0)
16:53:20.668 [main] INFO org.stagemonitor.core.Stagemonitor - OK   - ElasticsearchTracingPlugin (version 0.88.0)
16:53:20.668 [main] INFO org.stagemonitor.core.Stagemonitor - OK   - JdbcPlugin (version 0.88.0)
16:53:20.668 [main] INFO org.stagemonitor.core.Stagemonitor - OK   - JvmPlugin (version 0.88.0)
16:53:20.668 [main] INFO org.stagemonitor.core.Stagemonitor - OK   - ServletPlugin (version 0.88.0)
16:53:20.668 [main] INFO org.stagemonitor.core.Stagemonitor - OK   - SoapTracingPlugin (version 0.88.0)
16:53:20.668 [main] INFO org.stagemonitor.core.Stagemonitor - OK   - Startup 
16:53:20.668 [main] INFO org.stagemonitor.core.Stagemonitor - OK   - TracingPlugin (version 0.88.0)
16:53:20.668 [main] INFO org.stagemonitor.core.configuration.ConfigurationLogger - # stagemonitor configuration, listing non-default values:
16:53:20.668 [main] INFO org.stagemonitor.core.configuration.ConfigurationLogger - stagemonitor.applicationName: CAAS WEB (source: stagemonitor.properties)
16:53:20.668 [main] INFO org.stagemonitor.core.configuration.ConfigurationLogger - stagemonitor.instanceName: dev (source: stagemonitor.properties)
16:53:20.668 [main] INFO org.stagemonitor.core.configuration.ConfigurationLogger - stagemonitor.instrument.include: com.shj.caas (source: stagemonitor.properties)

![1](https://user-images.githubusercontent.com/28695335/36891521-e2694e58-1e3c-11e8-9558-a5189df34041.png)

I also check the source code, found the corresponding class file have the method which refer there is no suth method.
![2](https://user-images.githubusercontent.com/28695335/36891622-3a9c9a9e-1e3d-11e8-93fd-048317ca76bb.png)
Please give the solution!

**Comment by yacota** [comment]
After changing the pom dependencies have you made a mvn clean?

In master, also in 0.88.0 you can check that startActive is called with a boolean parameter
https://github.com/stagemonitor/stagemonitor/blob/master/stagemonitor-web-servlet/src/main/java/org/stagemonitor/web/servlet/MonitoredHttpRequest.java#L99

final Scope scope = spanBuilder.startActive(true);

And also you can check that in https://github.com/stagemonitor/stagemonitor/blob/master/stagemonitor-tracing/src/main/java/org/stagemonitor/tracing/wrapper/SpanWrappingTracer.java#L166

There is no startActive method without a boolean parameter.

**Comment by liebhaeuser** [comment]
I made a mistake in the 0.88.x branch and did not include the jaeger dependency changes. I am going to correct that in Release 0.88.1 that I am building right now. I'm terribly sorry for that!
