### ISSUE TITLE
Application startup issue due to stagemonitor properties   

### ISSUE THREAD

**Issue by ychandu** [stagemonitor/stagemonitor#409]
Application startup issue due to stagemonitor properties   

WARN [configuration-reloader] org.stagemonitor.configuration.ConfigurationRegistry - Illegal access: this web application instance has been stopped already. Could not load [stagemonitor.properties]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access. (this exception is ignored)
java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [stagemonitor.properties]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1311) ~[?:?]
        at org.apache.catalina.loader.WebappClassLoaderBase.getResourceAsStream(WebappClassLoaderBase.java:1045) ~[?:?]
        at org.stagemonitor.configuration.source.PropertyFileConfigurationSource.getFromClasspath(PropertyFileConfigurationSource.java:74) ~[stagemonitor-configuration-0.87.5.jar:0.87.5]
        at org.stagemonitor.configuration.source.PropertyFileConfigurationSource.getProperties(PropertyFileConfigurationSource.java:65) ~[stagemonitor-configuration-0.87.5.jar:0.87.5]
        at org.stagemonitor.configuration.source.PropertyFileConfigurationSource.reload(PropertyFileConfigurationSource.java:40) ~[stagemonitor-configuration-0.87.5.jar:0.87.5]
        at org.stagemonitor.configuration.ConfigurationRegistry.reload(ConfigurationRegistry.java:320) [stagemonitor-configuration-0.87.5.jar:0.87.5]
        at org.stagemonitor.configuration.ConfigurationRegistry.reloadDynamicConfigurationOptions(ConfigurationRegistry.java:314) [stagemonitor-configuration-0.87.5.jar:0.87.5]
        at org.stagemonitor.configuration.ConfigurationRegistry$2.run(ConfigurationRegistry.java:267) [stagemonitor-configuration-0.87.5.jar:0.87.5]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_171]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_171]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

**Comment by ychandu** [comment]
is there any dependency on the following issue?
018-05-30 14:46:23.110 WARN  localhost-startStop-1 org.springframework.web.context.support.XmlWebApplicationContext [] - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'searchRepository': Cannot resolve reference to bean 'solrClient' while setting bean property 'solrClient'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'solrClient': Invocation of init method failed; nested exception is java.lang.VerifyError: Bad return type
Exception Details:
  Location:
    org/apache/solr/client/solrj/impl/HttpClientUtil.createClient(Lorg/apache/solr/common/params/SolrParams;)Lorg/apache/http/impl/client/CloseableHttpClient; @57: areturn
  Reason:
    Type 'org/apache/http/impl/client/SystemDefaultHttpClient' (current frame, stack[0]) is not assignable to 'org/apache/http/impl/client/CloseableHttpClient' (from method signature)
  Current Frame:
    bci: @57
    flags: { }
    locals: { 'org/apache/solr/common/params/SolrParams', 'org/apache/solr/common/params/ModifiableSolrParams', 'org/apache/http/impl/client/SystemDefaultHttpClient' }
    stack: { 'org/apache/http/impl/client/SystemDefaultHttpClient' }

**Comment by ychandu** [comment]
I am able to resolve this. Thank you.

**Comment by liebhaeuser** [comment]
How did you solve it?

**Comment by ychandu** [comment]
httpclient.jar inside the stagemonitor-tracing-elasticsearch causing the issue. so excluded it 

<dependency>   		
      		<groupId>org.stagemonitor</groupId>
      		<artifactId>stagemonitor-tracing-elasticsearch</artifactId>
      		<version>0.88.4</version>
      		<exclusions>
      			<exclusion>
      				<groupId>org.apache.httpcomponents</groupId>
      				<artifactId>httpclient</artifactId>
      			</exclusion>
      		</exclusions>
   		</dependency>
