### ISSUE TITLE
Failed to perform runtime attachment of the stagemonitor agent

### ISSUE THREAD

**Issue by kgoedert** [stagemonitor/stagemonitor#415]
Hi,

I am trying to use stagemonitor version 0.88.4 in a wildfly version 13. The byte buddy jar is being configured like this:

```
JAVA_OPTS:  -server -Xms64m -Xmx512m -Djava.net.preferIPv4Stack=true -Dsun.security.ssl.allowUnsafeRenegotiation=true -Djava.awt.headless=true -javaagent:/opt/bytebuddy/byte-buddy-agent-1.7.9.jar -Dstagemonitor.property.overrides=stagemonitor-dev.properties -agentlib:jdwp=transport=dt_socket,address=8787,server=y,suspend=n

```
I get the following error while the server is starting up:

```
12:23:25,047 INFO  [org.stagemonitor.core.StagemonitorCoreConfigurationSourceInitializer] (MSC service thread 1-1) try loading of default property overrides: 'stagemonitor-dev.properties'
wildfly_1  | 12:23:25,125 WARN  [org.stagemonitor.core.instrument.AgentAttacher] (MSC service thread 1-1) Failed to perform runtime attachment of the stagemonitor agent. Make sure that you run your application with a JDK (not a JRE).To make stagemonitor work with a JRE, you have to add the following command line argument to the start of the JVM: -javaagent:/path/to/byte-buddy-agent-<version>.jar. The version of the agent depends on the version of stagemonitor. You can download the appropriate agent for the stagemonitor version you are using here: http://central.maven.org/maven2/net/bytebuddy/byte-buddy-agent/1.7.9/byte-buddy-agent-1.7.9.jar: java.lang.NoClassDefFoundError: __redirected/org/stagemonitor/dispatcher/Dispatcher
wildfly_1  | 	at org.stagemonitor.core.instrument.AgentAttacher.initInstrumentation(AgentAttacher.java:152)
wildfly_1  | 	at org.stagemonitor.core.instrument.AgentAttacher.performRuntimeAttachment(AgentAttacher.java:83)
wildfly_1  | 	at org.stagemonitor.core.Stagemonitor.reset(Stagemonitor.java:315)
wildfly_1  | 	at org.stagemonitor.core.Stagemonitor.reset(Stagemonitor.java:297)
wildfly_1  | 	at org.stagemonitor.core.Stagemonitor.init(Stagemonitor.java:58)
wildfly_1  | 	at org.stagemonitor.core.instrument.StagemonitorRuntimeAgentAttacherDriver.<clinit>(StagemonitorRuntimeAgentAttacherDriver.java:23)
wildfly_1  | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
wildfly_1  | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
wildfly_1  | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
wildfly_1  | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
wildfly_1  | 	at org.jboss.as.connector.deployers.ds.processors.DriverProcessor.deploy(DriverProcessor.java:65)
wildfly_1  | 	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:143)
wildfly_1  | 	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1736)
wildfly_1  | 	at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1698)
wildfly_1  | 	at org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1556)
wildfly_1  | 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
wildfly_1  | 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
wildfly_1  | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
wildfly_1  | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1364)
wildfly_1  | 	at java.lang.Thread.run(Thread.java:748)
wildfly_1  | Caused by: java.lang.ClassNotFoundException: __redirected.org.stagemonitor.dispatcher.Dispatcher from [Module "deployment.cadu2.war" from Service Module Loader]
wildfly_1  | 	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:255)
wildfly_1  | 	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
wildfly_1  | 	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
wildfly_1  | 	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
wildfly_1  | 	... 20 more

```

But the plugins seem to startup up ok.

```
egister cpu usage. (com.sun.management.OperatingSystemMXBean from [Module "deployment.cadu2.war" from Service Module Loader])
wildfly_1  | 12:23:25,380 INFO  [org.stagemonitor.web.servlet.ServletPlugin] (MSC service thread 1-1) Initializing ClientSpanExtensions [org.stagemonitor.web.servlet.eum.WeaselClientSpanExtension@4f9e07e4]
wildfly_1  | 12:23:25,380 INFO  [org.stagemonitor.core.Stagemonitor] (MSC service thread 1-1) # stagemonitor status
wildfly_1  | 12:23:25,381 INFO  [org.stagemonitor.core.Stagemonitor] (MSC service thread 1-1) System information: Java 1.8.0_161 (Oracle Corporation) Linux 4.10.0-38-generic
wildfly_1  | 12:23:25,381 INFO  [org.stagemonitor.core.Stagemonitor] (MSC service thread 1-1) FAIL - Agent attachment (Failed to perform runtime attachment of the stagemonitor agent. Make sure that you run your application with a JDK (not a JRE).To make stagemonitor work with a JRE, you have to add the following command line argument to the start of the JVM: -javaagent:/path/to/byte-buddy-agent-<version>.jar. The version of the agent depends on the version of stagemonitor. You can download the appropriate agent for the stagemonitor version you are using here: http://central.maven.org/maven2/net/bytebuddy/byte-buddy-agent/1.7.9/byte-buddy-agent-1.7.9.jar)
wildfly_1  | 12:23:25,381 INFO  [org.stagemonitor.core.Stagemonitor] (MSC service thread 1-1) OK   - CorePlugin (version 0.88.4)
wildfly_1  | 12:23:25,382 INFO  [org.stagemonitor.core.Stagemonitor] (MSC service thread 1-1) OK   - ElasticsearchTracingPlugin (version 0.88.4)
wildfly_1  | 12:23:25,382 INFO  [org.stagemonitor.core.Stagemonitor] (MSC service thread 1-1) OK   - JdbcPlugin (version 0.88.4)
wildfly_1  | 12:23:25,382 INFO  [org.stagemonitor.core.Stagemonitor] (MSC service thread 1-1) OK   - JvmPlugin (version 0.88.4)
wildfly_1  | 12:23:25,382 INFO  [org.stagemonitor.core.Stagemonitor] (MSC service thread 1-1) OK   - ServletPlugin (version 0.88.4)
wildfly_1  | 12:23:25,382 INFO  [org.stagemonitor.core.Stagemonitor] (MSC service thread 1-1) OK   - SoapTracingPlugin (version 0.88.4)
wildfly_1  | 12:23:25,382 INFO  [org.stagemonitor.core.Stagemonitor] (MSC service thread 1-1) OK   - Startup 
wildfly_1  | 12:23:25,382 INFO  [org.stagemonitor.core.Stagemonitor] (MSC service thread 1-1) OK   - TracingPlugin (version 0.88.4)
wildfly_1  | 12:23:25,383 INFO  [org.stagemonitor.core.configuration.ConfigurationLogger] (MSC service thread 1-1) # stagemonitor configuration, listing non-default values:
wildfly_1  | 12:23:25,383 INFO  [org.stagemonitor.core.configuration.ConfigurationLogger] (MSC service thread 1-1) stagemonitor.applicationName: Cadu2 (source: stagemonitor.properties)
wildfly_1  | 12:23:25,383 INFO  [org.stagemonitor.core.configuration.ConfigurationLogger] (MSC service thread 1-1) stagemonitor.instanceName: dev (source: stagemonitor-dev.properties)
```

What is causing the exception?

Kelly

**Comment by liebhaeuser** [comment]
Thanks for reporting the issue, I will have a look at it.

**Comment by liebhaeuser** [comment]
Hi. It's still working in Wildfly 12.0.0.Final. I'll have a look at the changes in Wildfly 13.

**Comment by thomasbecker** [comment]
@liebhaeuser Any update on this one?

**Comment by svenruppert** [comment]
We are working internally on JDK11 ff Support.
