### ISSUE TITLE
NoSuchMethod Error AgentBuilder - Can't Start Web Application

### ISSUE THREAD

**Issue by echua** [stagemonitor/stagemonitor#444]
Spring MVC
SpringBoot 2.1.2

Trying to use the PetClinic example but still cannot get this work. I get errors.  Also, for the application, I am using the SpringBootServletInitializer rather than the ServletContextInitializer like in the PetClinic example. 

@SpringBootApplication
@EnableScheduling
public class Application extends SpringBootServletInitializer {

	public static void main(String[] args) {
		// Stagemonitor.init();  ****
		SpringApplication.run(Application.class, args);
	}

	public Application() {
		super();
		setRegisterErrorPageFilter(false);
	}

	@Override
	protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
		return application.sources(Application.class);
	}

	@Override
	public void onStartup(ServletContext servletContext) throws ServletException {
		super.onStartup(servletContext);
		......
	}
	

[m java.lang.NoSuchMethodError: net.bytebuddy.agent.builder.AgentBuilder$Identified$Extendable.asDecorator()Lnet/bytebuddy/agent/builder/AgentBuilder;
        at org.stagemonitor.core.instrument.AgentAttacher.initByteBuddyClassFileTransformer(AgentAttacher.java:217) ~[stagemonitor-core-0.88.9.jar:0.88.9]
        at org.stagemonitor.core.instrument.AgentAttacher.performRuntimeAttachment(AgentAttacher.java:85) ~[stagemonitor-core-0.88.9.jar:0.88.9]
        at org.stagemonitor.core.Stagemonitor.reset(Stagemonitor.java:315) ~[stagemonitor-core-0.88.9.jar:0.88.9]
        at org.stagemonitor.core.Stagemonitor.reset(Stagemonitor.java:297) ~[stagemonitor-core-0.88.9.jar:0.88.9]
        at org.stagemonitor.core.Stagemonitor.init(Stagemonitor.java:58) [stagemonitor-core-0.88.9.jar:0.88.9]
        at org.stagemonitor.web.servlet.ServletPlugin$Initializer.onStartup(ServletPlugin.java:503) [stagemonitor-web-servlet-0.88.9.jar:0.88.9]

POM file, I copied from the example.
       <dependency>
	      <groupId>org.stagemonitor</groupId>
	      <artifactId>stagemonitor-web-servlet</artifactId>
	      <version>${stagemonitor.version}</version>
	    </dependency>
	    <dependency>
	      <groupId>org.stagemonitor</groupId>
	      <artifactId>stagemonitor-tracing-elasticsearch</artifactId>
	      <version>${stagemonitor.version}</version>
	    </dependency>
	    <dependency>
	      <groupId>org.stagemonitor</groupId>
	      <artifactId>stagemonitor-logging</artifactId>
	      <version>${stagemonitor.version}</version>
	    </dependency>
	    <dependency>
	      <groupId>org.stagemonitor</groupId>
	      <artifactId>stagemonitor-os</artifactId>
	      <version>${stagemonitor.version}</version>
	    </dependency>
	    <dependency>
	      <groupId>org.stagemonitor</groupId>
	      <artifactId>stagemonitor-alerting</artifactId>
	      <version>${stagemonitor.version}</version>
	    </dependency>
	    <dependency>
	      <groupId>net.sf.uadetector</groupId>
	      <artifactId>uadetector-resources</artifactId>
	      <version>2014.10</version>
	    </dependency>

**Comment by jpfourny** [comment]
Can you confirm the version of ByteBuddy? That method was removed in later versions.

**Comment by echua** [comment]
Checking the lib directory.

byte-buddy-1.9.7.jar           
byte-buddy-agent-1.9.7.jar

**Comment by jpfourny** [comment]
That explains it. Stagemonitor will not work with anything above 1.8.11, in my experience. 1.9.x contains binary incompatible changes and 1.8.12+ seems to cause test failures and JVM crashes (at least with IBM OpenJ9).

**Comment by echua** [comment]
What do you suggest to fix this?

**Comment by jpfourny** [comment]
Down-grade ByteBuddy to 1.8.11.
