### ISSUE TITLE
Failed to perform runtime attachment of the stagemonitor agent with WildFly 15 and JDK 11

### ISSUE THREAD

**Issue by mrts** [stagemonitor/stagemonitor#445]
This may be duplicate of #415.

As far as I understand from the wiki, StageMonitor should work out of the box with JDK >9 with modern application servers with no `-javaagent` parameters required. Please correct me if I'm wrong.

I want to use StageMonitor during development, not with the Elasticsearch/Kibana request analysis dashboard.

## Environment

- StageMonitor v0.88.9
- JDK 11 (jdk-11.0.2+9)
- Java EE 7 Vaadin 13 CDI application
- WildFly 15 application server

## Steps to reproduce and demo application

Demo application is here: https://gitlab.com/mrts/vaadin-with-stagemonitor

1. Install latest JDK 11 from AdoptOpenJDK
1. Install WildFly 15
1. Clone sample application with `git clone https://gitlab.com/mrts/vaadin-with-stagemonitor`
1. Build with `cd vaadin-with-stagemonitor && mvn package`
1. Deploy to WildFly 15

## Expected/actual

**Expected**: StageMonitor agent attaches to WildFly successfully and is able to monitor CPU usage and display the request call tree.

**Actual**: StageMonitor agent fails to attach to WildFly with `java.lang.NoClassDefFoundError: __redirected/org/stagemonitor/dispatcher/Dispatcher`, fails to register CPU usage monitor with `Could not register cpu usage due to ClassNotFoundException. Please make sure that com.sun.management.OperatingSystemMXBean can be loaded` and complains that it is not configured.

## Startup logs

```
14:26:01,466 WARN  [org.stagemonitor.core.instrument.AgentAttacher] (MSC service thread 1-3) Failed to perform runtime attachment of the stagemonitor agent. Make sure that you run your application with a JDK (not a JRE).To make stagemonitor work with a JRE, you have to add the following command line argument to the start of the JVM: -javaagent:/path/to/byte-buddy-agent-<version>.jar. The version of the agent depends on the version of stagemonitor. You can download the appropriate agent for the stagemonitor version you are using here: http://central.maven.org/maven2/net/bytebuddy/byte-buddy-agent/1.9.3/byte-buddy-agent-1.9.3.jar: java.lang.NoClassDefFoundError: __redirected/org/stagemonitor/dispatcher/Dispatcher
	at deployment.vaadin-with-stagemonitor-1.0-SNAPSHOT.war//org.stagemonitor.core.instrument.AgentAttacher.initInstrumentation(AgentAttacher.java:152)
	at deployment.vaadin-with-stagemonitor-1.0-SNAPSHOT.war//org.stagemonitor.core.instrument.AgentAttacher.performRuntimeAttachment(AgentAttacher.java:83)
	at deployment.vaadin-with-stagemonitor-1.0-SNAPSHOT.war//org.stagemonitor.core.Stagemonitor.reset(Stagemonitor.java:315)
	at deployment.vaadin-with-stagemonitor-1.0-SNAPSHOT.war//org.stagemonitor.core.Stagemonitor.reset(Stagemonitor.java:297)
	at deployment.vaadin-with-stagemonitor-1.0-SNAPSHOT.war//org.stagemonitor.core.Stagemonitor.init(Stagemonitor.java:58)
	at deployment.vaadin-with-stagemonitor-1.0-SNAPSHOT.war//org.stagemonitor.core.instrument.StagemonitorRuntimeAgentAttacherDriver.<clinit>(StagemonitorRuntimeAgentAttacherDriver.java:23)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.jboss.as.connector@15.0.0.Final//org.jboss.as.connector.deployers.ds.processors.DriverProcessor.deploy(DriverProcessor.java:65)
	at org.jboss.as.server@7.0.0.Final//org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:144)
	at org.jboss.msc@1.4.5.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1738)
	at org.jboss.msc@1.4.5.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1700)
	at org.jboss.msc@1.4.5.Final//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1558)
	at org.jboss.threads@2.3.2.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.3.2.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
	at org.jboss.threads@2.3.2.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
	at org.jboss.threads@2.3.2.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1364)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: __redirected.org.stagemonitor.dispatcher.Dispatcher from [Module "deployment.vaadin-with-stagemonitor-1.0-SNAPSHOT.war" from Service Module Loader]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:255)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	... 20 more

14:26:01,468 INFO  [org.stagemonitor.core.Stagemonitor] (MSC service thread 1-3) Measurement Session is initialized: [application=My Application] [instance=My Instance] [host=WMLI120601]
14:26:01,482 INFO  [org.stagemonitor.core.CorePlugin] (MSC service thread 1-3) Not sending metrics to InfluxDB (url=null, interval=60s)
14:26:01,494 WARN  [org.stagemonitor.jvm.JvmPlugin] (MSC service thread 1-3) Could not register cpu usage due to ClassNotFoundException. Please make sure that com.sun.management.OperatingSystemMXBean can be loaded.
14:26:01,496 INFO  [org.stagemonitor.tracing.TracingPlugin] (MSC service thread 1-3) No OpenTracing implementation found. Falling back to DefaultTracerImpl. This is fine if you just want to use stagemonitor for development, for example with the in-browser-widget. If you want to report your traces to Elasticsearch, add a dependency to stagemonitor-tracing-elasticsearch. If you want to report to Zipkin, add stagemonitor-tracing-zipkin.
14:26:01,519 INFO  [org.stagemonitor.web.servlet.ServletPlugin] (MSC service thread 1-3) Initializing ClientSpanExtensions [org.stagemonitor.web.servlet.eum.WeaselClientSpanExtension@4cb4b97a]
14:26:01,520 INFO  [org.stagemonitor.core.Stagemonitor] (MSC service thread 1-3) # stagemonitor status
14:26:01,520 INFO  [org.stagemonitor.core.Stagemonitor] (MSC service thread 1-3) System information: Java 11.0.2 (AdoptOpenJDK) Windows 10 10.0
14:26:01,521 INFO  [org.stagemonitor.core.Stagemonitor] (MSC service thread 1-3) FAIL - Agent attachment (Failed to perform runtime attachment of the stagemonitor agent. Make sure that you run your application with a JDK (not a JRE).To make stagemonitor work with a JRE, you have to add the following command line argument to the start of the JVM: -javaagent:/path/to/byte-buddy-agent-<version>.jar. The version of the agent depends on the version of stagemonitor. You can download the appropriate agent for the stagemonitor version you are using here: http://central.maven.org/maven2/net/bytebuddy/byte-buddy-agent/1.9.3/byte-buddy-agent-1.9.3.jar)
14:26:01,521 INFO  [org.stagemonitor.core.Stagemonitor] (MSC service thread 1-3) OK   - CorePlugin (version 0.88.9)
14:26:01,521 INFO  [org.stagemonitor.core.Stagemonitor] (MSC service thread 1-3) OK   - JdbcPlugin (version 0.88.9)
14:26:01,521 INFO  [org.stagemonitor.core.Stagemonitor] (MSC service thread 1-3) OK   - JvmPlugin (version 0.88.9)
14:26:01,521 INFO  [org.stagemonitor.core.Stagemonitor] (MSC service thread 1-3) OK   - ServletPlugin (version 0.88.9)
14:26:01,521 INFO  [org.stagemonitor.core.Stagemonitor] (MSC service thread 1-3) OK   - SoapTracingPlugin (version 0.88.9)
14:26:01,521 INFO  [org.stagemonitor.core.Stagemonitor] (MSC service thread 1-3) OK   - Startup 
14:26:01,521 INFO  [org.stagemonitor.core.Stagemonitor] (MSC service thread 1-3) OK   - TracingPlugin (version 0.88.9)
14:26:01,522 INFO  [org.stagemonitor.core.configuration.ConfigurationLogger] (MSC service thread 1-3) # stagemonitor configuration, listing non-default values:
14:26:01,522 WARN  [org.stagemonitor.core.configuration.ConfigurationLogger] (MSC service thread 1-3) stagemonitor has not been configured. Have a look at https://github.com/stagemonitor/stagemonitor/wiki/How-should-I-configure-stagemonitor%3F and https://github.com/stagemonitor/stagemonitor/wiki/Configuration-Options for further instructions
```

**Comment by mrts** [comment]
Adding `-javaagent:path-to/byte-buddy-agent-1.9.3.jar ` does not fix the error.

**Comment by thaarbach** [comment]
@mrts 
Sorry for the long wait. The reason, why the runtime attachment is not working depends on change in the wildfly modul class loaders. 
To run stagemonitor with wildfly 15 and Jdk 11 please add to JAVA_OPTS the following 
``` -Djboss.modules.system.pkgs=__redirected.org.stagemonitor.dispatcher```

Unfortunally Wildfly comes with an older bytebuddy version you have also to add 
```        <dependency>
            <groupId>net.bytebuddy</groupId>
            <artifactId>byte-buddy</artifactId>
            <version>1.8.22</version>
        </dependency>```
to your pom.xml

If you have any futher questions, please reopen this issue.
