### ISSUE TITLE
plain clone , clean build is not working..  failing tests

### ISSUE THREAD

**Issue by svenruppert** [stagemonitor/stagemonitor#450]
the test coverage should be checked

**Comment by svenruppert** [comment]
org.stagemonitor.tracing.freemarker.FreemarkerProfilingTransformerTest > testFreemarkerProfilingMethodCall FAILED
    org.junit.ComparisonFailure: expected:<"[test.ftl:1#t]emplateModel.getFoo(...> but was:<"[String org.stagemonitor.tracing.freemarker.FreemarkerProfilingTransformerTest$T]emplateModel.getFoo(...>
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at org.stagemonitor.tracing.freemarker.FreemarkerProfilingTransformerTest.testFreemarkerProfilingMethodCall(FreemarkerProfilingTransformerTest.java:48)

org.stagemonitor.tracing.freemarker.FreemarkerProfilingTransformerTest > testFreemarkerProfiling FAILED
    org.junit.ComparisonFailure: expected:<"[test.ftl:1#templateModel.foo]"> but was:<"[String org.stagemonitor.tracing.freemarker.FreemarkerProfilingTransformerTest$TemplateModel.getFoo()]">
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at org.stagemonitor.tracing.freemarker.FreemarkerProfilingTransformerTest.testFreemarkerProfiling(FreemarkerProfilingTransformerTest.java:30)

100 tests completed, 2 failed, 2 skipped

> Task :stagemonitor-tracing:test FAILED
Execution failed for task ':stagemonitor-tracing:test'.
> There were failing tests. See the report at: file:///Users/svenruppert/Desktop/workspace/stagemonitor/stagemonitor/stagemonitor-tracing/build/reports/tests/test/index.html

**Comment by liebhaeuser** [comment]
I could reproduce the failing test within the IDE. Tests run fine in my environment if executed in a terminal: "./gradlew clean build".

**Comment by liebhaeuser** [comment]
`./gradlew :stagemonitor-tracing:cleanTest :stagemonitor-tracing:test --tests "org.stagemonitor.tracing.freemarker.FreemarkerProfilingTransformerTest.testFreemarkerProfiling"` is failing in terminal too.
