### ISSUE TITLE
No kibana 7 dashboard

### ISSUE THREAD

**Issue by cdalexndr** [stagemonitor/stagemonitor#456]
After following the installation documentation, and installing elasitcsearch 7.2.0 and kibana 7.2.0, when starting the app, no dashboard appears in kibana.
Found in logs some relevant warnings:
```
2019-07-26 00:16:59,345 WARN  [elasticsearch-tasks] http://localhost:9200/.kibana/doc/index-pattern:stagemonitor-metrics-*
java.io.FileNotFoundException: http://localhost:9200/.kibana/doc/index-pattern:stagemonitor-metrics-*
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1915)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
	at org.stagemonitor.core.util.HttpClient.send(HttpClient.java:77)
	at org.stagemonitor.core.elasticsearch.ElasticsearchClient.getJson(ElasticsearchClient.java:99)
	at org.stagemonitor.core.elasticsearch.ElasticsearchClient.getJson(ElasticsearchClient.java:95)
	at org.stagemonitor.core.elasticsearch.ElasticsearchClient.fetchCurrentKibanaIndexPatternConfiguration(ElasticsearchClient.java:191)
	at org.stagemonitor.core.elasticsearch.ElasticsearchClient.updateKibanaIndexPattern(ElasticsearchClient.java:176)
	at org.stagemonitor.core.CoreElasticsearchInitializer.manageMetricsIndex(CoreElasticsearchInitializer.java:63)
	at org.stagemonitor.core.CoreElasticsearchInitializer.onElasticsearchFirstAvailable(CoreElasticsearchInitializer.java:31)
	at org.stagemonitor.core.elasticsearch.AbstractElasticsearchInitializer.onElasticsearchAvailable(AbstractElasticsearchInitializer.java:17)
	at org.stagemonitor.core.elasticsearch.ElasticsearchClient$CheckEsAvailability$2.handleResponse(ElasticsearchClient.java:582)
	at org.stagemonitor.core.elasticsearch.ElasticsearchClient$CheckEsAvailability$2.handleResponse(ElasticsearchClient.java:558)
	at org.stagemonitor.core.util.http.HttpRequestBuilder$5.handleResponse(HttpRequestBuilder.java:161)
	at org.stagemonitor.core.util.HttpClient.send(HttpClient.java:79)
	at org.stagemonitor.core.elasticsearch.ElasticsearchClient$CheckEsAvailability.run(ElasticsearchClient.java:556)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
2019-07-26 00:16:59,422 WARN  [elasticsearch-tasks] http://localhost:9200/.kibana/doc/index-pattern:stagemonitor-metrics-*: 400 {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Rejecting mapping update to [.kibana_1] as the final mapping would have more than 1 type: [_doc, doc]"}],"type":"illegal_argument_exception","reason":"Rejecting mapping update to [.kibana_1] as the final mapping would have more than 1 type: [_doc, doc]"},"status":400}
```
Similar warnings for "stagemonitor-spans-*"

```
2019-07-26 00:16:58,611 INFO  [restartedMain] # stagemonitor status
2019-07-26 00:16:58,612 INFO  [restartedMain] System information: Java 12.0.2 (Oracle Corporation) Windows 10 10.0
2019-07-26 00:16:58,615 INFO  [restartedMain] OK   - Agent attachment 
2019-07-26 00:16:58,615 INFO  [restartedMain] OK   - AlertingPlugin (version 0.88.9)
2019-07-26 00:16:58,615 INFO  [restartedMain] OK   - CorePlugin (version 0.88.9)
2019-07-26 00:16:58,616 INFO  [restartedMain] OK   - ElasticsearchTracingPlugin (version 0.88.9)
2019-07-26 00:16:58,616 INFO  [restartedMain] OK   - JdbcPlugin (version 0.88.9)
2019-07-26 00:16:58,616 INFO  [restartedMain] OK   - JvmPlugin (version 0.88.9)
2019-07-26 00:16:58,616 INFO  [restartedMain] OK   - LoggingPlugin (version 0.88.9)
2019-07-26 00:16:58,617 INFO  [restartedMain] OK   - ServletPlugin (version 0.88.9)
2019-07-26 00:16:58,617 INFO  [restartedMain] OK   - SoapTracingPlugin (version 0.88.9)
2019-07-26 00:16:58,617 INFO  [restartedMain] OK   - Startup 
2019-07-26 00:16:58,618 INFO  [restartedMain] OK   - TracingPlugin (version 0.88.9)
2019-07-26 00:16:58,619 INFO  [restartedMain] # stagemonitor configuration, listing non-default values:
2019-07-26 00:16:58,619 INFO  [restartedMain] stagemonitor.applicationName: PSE (source: stagemonitor.properties)
2019-07-26 00:16:58,619 INFO  [restartedMain] stagemonitor.instanceName: dev (source: stagemonitor.properties)
2019-07-26 00:16:58,620 INFO  [restartedMain] stagemonitor.reporting.elasticsearch.url: http://localhost:9200 (source: stagemonitor.properties)
2019-07-26 00:16:58,620 WARN  [restartedMain] Detected usage of an old configuration key: 'stagemonitor.elasticsearch.url'. Please use 'stagemonitor.reporting.elasticsearch.url' instead.
2019-07-26 00:16:58,621 INFO  [restartedMain] stagemonitor.instrument.include: pse (source: stagemonitor.properties)
```

**Comment by liebhaeuser** [comment]
We are currently working to support Elasticsearch 7. There is already a es7 branch.

**Comment by liebhaeuser** [comment]
We merged the changes and ES 7 support will be part of the next release.
