### ISSUE TITLE
URGENT!!! - Unable to see kibana/grafana dashboard for Petclinic app

### ISSUE THREAD

**Issue by sendev1** [stagemonitor/stagemonitor#485]
Hello,

I have followed your installation guide and setup docker container for elasticsearch, kibana and grafana.. When I tried to start the Petclinic app from you github I am getting following logs and I am not able to see the kibana/grafana dashboards.

22:12:29.461 [main] WARN org.stagemonitor.tracing.soap.SoapHandlerTransformer - SoapTracingPlugin is disabled because of missing com.sun.xml.ws:jaxws-rt. If you running Java >= 11 and you want monitor SOAP Calls then make sure com.sun.xml.ws:jaxws-rt is in classpath
22:12:30.025 [main] INFO org.stagemonitor.core.Stagemonitor - Measurement Session is initialized: [application=Spring Petclinic] [instance=dev] [host=DESKTOP-RSUQE98]
22:12:30.082 [elasticsearch-tasks] INFO org.stagemonitor.core.elasticsearch.ElasticsearchClient - wait 1s until core plugin is initialized
22:12:30.088 [main] INFO org.stagemonitor.core.CorePlugin - Not sending metrics to InfluxDB (url=null, interval=60s)
22:12:30.151 [async-grafana] WARN org.stagemonitor.core.util.http.ErrorLoggingResponseHandler - http://localhost:3000/api/datasources: 403 {"message":"Permission denied"}
22:12:30.187 [async-grafana] WARN org.stagemonitor.core.util.http.ErrorLoggingResponseHandler - http://localhost:3000/api/dashboards/db: 403 {"message":"Permission denied"}
22:12:30.295 [async-grafana] WARN org.stagemonitor.core.util.http.ErrorLoggingResponseHandler - http://localhost:3000/api/dashboards/db: 403 {"message":"Permission denied"}
22:12:30.328 [async-grafana] WARN org.stagemonitor.core.util.http.ErrorLoggingResponseHandler - http://localhost:3000/api/dashboards/db: 403 {"message":"Permission denied"}
22:12:30.889 [async-grafana] WARN org.stagemonitor.core.util.http.ErrorLoggingResponseHandler - http://localhost:3000/api/dashboards/db: 403 {"message":"Permission denied"}
22:12:30.919 [async-grafana] WARN org.stagemonitor.core.util.http.ErrorLoggingResponseHandler - http://localhost:3000/api/dashboards/db: 403 {"message":"Permission denied"}
22:12:30.976 [main] INFO org.stagemonitor.alerting.AlertingPlugin - Using ElasticsearchIncidentRepository for storing incidents.
22:12:30.986 [main] INFO org.stagemonitor.web.servlet.ServletPlugin - Initializing ClientSpanExtensions [org.stagemonitor.web.servlet.eum.WeaselClientSpanExtension@8243223e]
22:12:30.986 [main] INFO org.stagemonitor.core.Stagemonitor - # stagemonitor status
22:12:30.986 [main] INFO org.stagemonitor.core.Stagemonitor - System information: Java 11.0.11 (AdoptOpenJDK) Linux 4.19.128-microsoft-standard
22:12:30.988 [main] INFO org.stagemonitor.core.Stagemonitor - OK   - Agent attachment 
22:12:30.988 [main] INFO org.stagemonitor.core.Stagemonitor - OK   - AlertingPlugin (version 0.89.0)
22:12:30.988 [main] INFO org.stagemonitor.core.Stagemonitor - OK   - CorePlugin (version 0.89.0)
22:12:30.988 [main] INFO org.stagemonitor.core.Stagemonitor - OK   - ElasticsearchTracingPlugin (version 0.89.0)
22:12:30.988 [main] INFO org.stagemonitor.core.Stagemonitor - OK   - JdbcPlugin (version 0.89.0)
22:12:30.988 [main] INFO org.stagemonitor.core.Stagemonitor - OK   - JvmPlugin (version 0.89.0)
22:12:30.988 [main] INFO org.stagemonitor.core.Stagemonitor - OK   - LoggingPlugin (version 0.89.0)
22:12:30.988 [main] INFO org.stagemonitor.core.Stagemonitor - OK   - OsPlugin (version 0.89.0)
22:12:30.988 [main] INFO org.stagemonitor.core.Stagemonitor - OK   - ServletPlugin (version 0.89.0)
22:12:30.988 [main] INFO org.stagemonitor.core.Stagemonitor - OK   - SoapTracingPlugin (version 0.89.0)
22:12:30.988 [main] INFO org.stagemonitor.core.Stagemonitor - OK   - Startup 
22:12:30.989 [main] INFO org.stagemonitor.core.Stagemonitor - OK   - TracingPlugin (version 0.89.0)
22:12:30.990 [main] INFO org.stagemonitor.core.configuration.ConfigurationLogger - # stagemonitor configuration, listing non-default values:
22:12:30.991 [main] INFO org.stagemonitor.core.configuration.ConfigurationLogger - stagemonitor.alerts.frequency: 10 (source: stagemonitor.properties)
22:12:30.991 [main] INFO org.stagemonitor.core.configuration.ConfigurationLogger - stagemonitor.reporting.interval.elasticsearch: 10 (source: stagemonitor.properties)
22:12:30.991 [main] INFO org.stagemonitor.core.configuration.ConfigurationLogger - stagemonitor.applicationName: Spring Petclinic (source: stagemonitor.properties)
22:12:30.991 [main] INFO org.stagemonitor.core.configuration.ConfigurationLogger - stagemonitor.instanceName: dev (source: stagemonitor.properties)
22:12:30.991 [main] INFO org.stagemonitor.core.configuration.ConfigurationLogger - stagemonitor.reporting.elasticsearch.url: http://localhost:9200 (source: stagemonitor.properties)
22:12:30.991 [main] INFO org.stagemonitor.core.configuration.ConfigurationLogger - stagemonitor.instrument.exclude: org.springframework.samples.petclinic.model (source: stagemonitor.properties)
22:12:30.992 [main] INFO org.stagemonitor.core.configuration.ConfigurationLogger - stagemonitor.instrument.include: org.springframework.samples.petclinic (source: stagemonitor.properties)
22:12:30.992 [main] INFO org.stagemonitor.core.configuration.ConfigurationLogger - stagemonitor.grafana.url: http://localhost:3000 (source: stagemonitor.properties)
22:12:30.992 [main] INFO org.stagemonitor.core.configuration.ConfigurationLogger - stagemonitor.grafana.apiKey: XXXX (source: stagemonitor.properties)
22:12:30.992 [main] INFO org.stagemonitor.core.configuration.ConfigurationLogger - stagemonitor.requestmonitor.http.parseUserAgent: true (source: stagemonitor.properties)
22:12:30.992 [main] WARN org.stagemonitor.core.configuration.ConfigurationLogger - Detected usage of deprecated configuration option 'stagemonitor.requestmonitor.http.parseUserAgent'. This option might be removed in the future. Please refer to the documentation about alternatives.
22:12:30.992 [main] INFO org.stagemonitor.core.configuration.ConfigurationLogger - stagemonitor.web.paths.excluded: /resources,/webjars,/dandelion (source: stagemonitor.properties)
22:12:30.992 [main] INFO org.stagemonitor.core.configuration.ConfigurationLogger - stagemonitor.eum.enabled: true (source: stagemonitor.properties)
22:12:31.020 [async-grafana] WARN org.stagemonitor.core.util.http.ErrorLoggingResponseHandler - http://localhost:3000/api/dashboards/db: 403 {"message":"Permission denied"}
22:12:31.085 [elasticsearch-tasks] INFO org.stagemonitor.core.elasticsearch.ElasticsearchClient - Elasticsearch Version: 5.6.0
22:12:31.087 [elasticsearch-tasks] DEBUG org.stagemonitor.core.util.VersionUtils - Parsed version: 5.6.0, got major version: 5 
22:12:31.087 [elasticsearch-tasks] INFO org.stagemonitor.core.elasticsearch.ElasticsearchClient - Elasticsearch is available again.
22:12:31.087 [elasticsearch-tasks] DEBUG org.stagemonitor.core.CoreElasticsearchInitializer - creating KibanaIndexAndMapping for ES 5...
The Class-Path manifest attribute in /home/sen/.m2/repository/javax/mail/mail/1.4.1/mail-1.4.1.jar referenced one or more files that do not exist: file:/home/sen/.m2/repository/javax/mail/mail/1.4.1/activation.jar
22:12:31.214 [elasticsearch-tasks] DEBUG org.stagemonitor.core.CoreElasticsearchInitializer - created KibanaIndexAndMapping for ES 5
22:12:31.215 [elasticsearch-tasks] DEBUG org.stagemonitor.core.elasticsearch.ElasticsearchClient - Sending index pattern kibana/5/stagemonitor-metrics-kibana-index-pattern.json to /.kibana/index-pattern/stagemonitor-metrics-*
Exception in thread "elasticsearch-tasks" java.lang.RuntimeException: java.lang.NullPointerException
        at org.stagemonitor.core.elasticsearch.ElasticsearchClient.modifyIndexTemplate(ElasticsearchClient.java:249)
        at org.stagemonitor.core.CoreElasticsearchInitializer.manageMetricsIndex(CoreElasticsearchInitializer.java:68)
        at org.stagemonitor.core.CoreElasticsearchInitializer.onElasticsearchFirstAvailable(CoreElasticsearchInitializer.java:31)
        at org.stagemonitor.core.elasticsearch.AbstractElasticsearchInitializer.onElasticsearchAvailable(AbstractElasticsearchInitializer.java:17)
        at org.stagemonitor.core.elasticsearch.ElasticsearchClient$CheckEsAvailability$2.handleResponse(ElasticsearchClient.java:597)
        at org.stagemonitor.core.elasticsearch.ElasticsearchClient$CheckEsAvailability$2.handleResponse(ElasticsearchClient.java:573)
        at org.stagemonitor.core.util.http.HttpRequestBuilder$5.handleResponse(HttpRequestBuilder.java:161)
        at org.stagemonitor.core.util.HttpClient.send(HttpClient.java:79)
        at org.stagemonitor.core.elasticsearch.ElasticsearchClient$CheckEsAvailability.run(ElasticsearchClient.java:571)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
        at java.base/java.util.TimerThread.run(Timer.java:506)
Caused by: java.lang.NullPointerException
        at org.stagemonitor.core.elasticsearch.ElasticsearchClient.modifyIndexTemplate(ElasticsearchClient.java:238)
        ... 10 more

              |\      _,,,--,,_
             /,`.-'`'   ._  \-;;,_
  _______ __|,4-  ) )_   .;.(__`'-'__     ___ __    _ ___ _______
 |       | '---''(_/._)-'(_\_)   |   |   |   |  |  | |   |       |
 |    _  |    ___|_     _|       |   |   |   |   |_| |   |       | __ _ _
 |   |_| |   |___  |   | |       |   |   |   |       |   |       | \ \ \ \
 |    ___|    ___| |   | |      _|   |___|   |  _    |   |      _|  \ \ \ \
 |   |   |   |___  |   | |     |_|       |   | | |   |   |     |_    ) ) ) )
 |___|   |_______| |___| |_______|_______|___|_|  |__|___|_______|  / / / /
 ==================================================================/_/_/_/

:: Built with Spring Boot :: 2.1.6.RELEASE

2021-05-13 22:12:31.695  INFO 7006 --- [  restartedMain] o.s.s.petclinic.PetClinicApplication     : Starting PetClinicApplication on DESKTOP-RSUQE98 with PID 7006 (/home/sen/workspace/spring-petclinic/target/classes started by sen in /home/sen/workspace/spring-petclinic)
2021-05-13 22:12:31.698  INFO 7006 --- [  restartedMain] o.s.s.petclinic.PetClinicApplication     : No active profile set, falling back to default profiles: default
2021-05-13 22:12:31.771  INFO 7006 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
2021-05-13 22:12:31.772  INFO 7006 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
2021-05-13 22:12:32.685  INFO 7006 --- [  restartedMain] o.s.j.ConnectionMonitoringTransformer    : TRANSFORM DataSource com.zaxxer.hikari.HikariDataSource (DefaultConnectionMonitoringTransformer)
2021-05-13 22:12:33.411  INFO 7006 --- [  restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2021-05-13 22:12:33.522  INFO 7006 --- [  restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 104ms. Found 4 repository interfaces.
2021-05-13 22:12:34.345  INFO 7006 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$d60d8c34] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2021-05-13 22:12:34.872  INFO 7006 --- [  restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2021-05-13 22:12:34.907  INFO 7006 --- [  restartedMain] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2021-05-13 22:12:34.908  INFO 7006 --- [  restartedMain] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.21]
2021-05-13 22:12:35.080  INFO 7006 --- [  restartedMain] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2021-05-13 22:12:35.080  INFO 7006 --- [  restartedMain] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 3308 ms
2021-05-13 22:12:35.599  INFO 7006 --- [  restartedMain] org.ehcache.core.EhcacheManager          : Cache 'vets' created in EhcacheManager.
2021-05-13 22:12:35.608  INFO 7006 --- [  restartedMain] org.ehcache.jsr107.Eh107CacheManager     : Registering Ehcache MBean javax.cache:type=CacheStatistics,CacheManager=urn.X-ehcache.jsr107-default-config,Cache=vets
2021-05-13 22:12:35.617  INFO 7006 --- [  restartedMain] org.ehcache.jsr107.Eh107CacheManager     : Registering Ehcache MBean javax.cache:type=CacheStatistics,CacheManager=urn.X-ehcache.jsr107-default-config,Cache=vets
2021-05-13 22:12:35.719  INFO 7006 --- [  restartedMain] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2021-05-13 22:12:35.728  WARN 7006 --- [  restartedMain] com.zaxxer.hikari.util.DriverDataSource  : Registered driver with driverClassName=org.hsqldb.jdbcDriver was not found, trying direct instantiation.
2021-05-13 22:12:36.036  INFO 7006 --- [  restartedMain] com.zaxxer.hikari.pool.PoolBase          : HikariPool-1 - Driver does not support get/set network timeout for connections. (feature not supported)
2021-05-13 22:12:36.038  INFO 7006 --- [  restartedMain] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2021-05-13 22:12:36.484  INFO 7006 --- [  restartedMain] o.s.w.s.c.ConfigurationServlet           : Registering configuration Endpoint /stagemonitor/configuration. You can dynamically change the configuration by issuing a POST request to /stagemonitor/configuration?key=stagemonitor.config.key&value=configValue&stagemonitor.password=password. If the password is not set, dynamically changing the configuration is not available. The password can be omitted if set to an empty string.
2021-05-13 22:12:36.493  INFO 7006 --- [  restartedMain] o.s.w.s.eum.ClientSpanJavaScriptServlet  : built new end user monitoring JavaScript, size=16198 bytes, etag="ef8c5ee0"
2021-05-13 22:12:36.555  INFO 7006 --- [  restartedMain] o.s.b.d.a.OptionalLiveReloadServer       : LiveReload server is running on port 35729
2021-05-13 22:12:36.713  INFO 7006 --- [  restartedMain] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [
        name: default
        ...]
2021-05-13 22:12:36.790  INFO 7006 --- [  restartedMain] org.hibernate.Version                    : HHH000412: Hibernate Core {5.3.10.Final}
2021-05-13 22:12:36.792  INFO 7006 --- [  restartedMain] org.hibernate.cfg.Environment            : HHH000206: hibernate.properties not found
2021-05-13 22:12:36.880  INFO 7006 --- [  restartedMain] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.0.4.Final}
2021-05-13 22:12:37.112  INFO 7006 --- [  restartedMain] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.HSQLDialect
2021-05-13 22:12:38.038  INFO 7006 --- [  restartedMain] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2021-05-13 22:12:38.423  INFO 7006 --- [  restartedMain] o.h.h.i.QueryTranslatorFactoryInitiator  : HHH000397: Using ASTQueryTranslatorFactory
2021-05-13 22:12:38.949  INFO 7006 --- [  restartedMain] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2021-05-13 22:12:39.017  WARN 7006 --- [  restartedMain] aWebConfiguration$JpaWebMvcConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
2021-05-13 22:12:39.646  INFO 7006 --- [  restartedMain] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 15 endpoint(s) beneath base path '/manage'
2021-05-13 22:12:39.764  INFO 7006 --- [  restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2021-05-13 22:12:39.766  INFO 7006 --- [  restartedMain] o.s.s.petclinic.PetClinicApplication     : Started PetClinicApplication in 8.51 seconds (JVM running for 12.001)
2021-05-13 22:13:50.038  INFO 7006 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2021-05-13 22:13:50.038  INFO 7006 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2021-05-13 22:13:50.061  INFO 7006 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 23 ms
log4j:WARN No appenders could be found for logger (freemarker.cache).
log4j:WARN Please initialize the log4j system properly.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.fasterxml.jackson.module.afterburner.util.MyClassLoader (file:/home/sen/.m2/repository/com/fasterxml/jackson/module/jackson-module-afterburner/2.9.9/jackson-module-afterburner-2.9.9.jar) to method java.lang.ClassLoader.findLoadedClass(java.lang.String)
WARNING: Please consider reporting this to the maintainers of com.fasterxml.jackson.module.afterburner.util.MyClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

![image](https://user-images.githubusercontent.com/68568448/118217614-71306800-b43b-11eb-9f40-86cec34c7502.png)

![image](https://user-images.githubusercontent.com/68568448/118217647-81e0de00-b43b-11eb-8ea1-f292acfe0f3a.png)

![image](https://user-images.githubusercontent.com/68568448/118217675-90c79080-b43b-11eb-9dde-429ad9938666.png)

![image](https://user-images.githubusercontent.com/68568448/118217698-9de47f80-b43b-11eb-9fde-8da3ad955318.png)

**Comment by sendev1** [comment]
![image](https://user-images.githubusercontent.com/68568448/118217774-c66c7980-b43b-11eb-988f-54228f5f61f5.png)
