### ISSUE TITLE
Integrate in Spring Application

### ISSUE THREAD

**Issue by jhiemer** [stagemonitor/stagemonitor#55]
Hi,
I did take look at the [0] and tried to use it a Spring application. What I am using is Spring MVC and Spring Data Rest. Currently I just want to monitor the request execution time as defined in [1]. I defined the aop.xml as following:

```xml
<!DOCTYPE aspectj PUBLIC
        "-//AspectJ//DTD//EN" "http://www.eclipse.org/aspectj/dtd/aspectj.dtd">
<aspectj>
    <weaver options="-Xlint:ignore -Xset:weaveJavaxPackages=true">
        <!-- exclude generated proxies -->
        <exclude within="*..*CGLIB*" />
        <exclude within="*..*$$*" />
        <exclude within="*..access$*" />
        <exclude within="com.sun.proxy..*" />
    </weaver>

    <aspects>
        <concrete-aspect name="profiler"
                         extends="org.stagemonitor.requestmonitor.profiler.ProfilingAspect">
            <pointcut name="methodsToProfile" expression="execution(* de.project.web..*(..)) 
            AND !within(de.project.model..*)"/>
        </concrete-aspect>
    </aspects>
</aspectj>
```
In web there is a package called Controller with a home Controller. I set breakpoints in RequestMonitor, but could not track the execution. In my Spring Project (Java configured) I have enabled: `@EnableLoadTimeWeaving` and `@EnableAspectJAutoProxy`. What I am missing? 

[0]https://github.com/stagemonitor/stagemonitor/tree/master/stagemonitor-requestmonitor
[1] https://github.com/stagemonitor/stagemonitor/blob/master/stagemonitor-requestmonitor/src/main/java/org/stagemonitor/requestmonitor/RequestMonitor.java

**Comment by felixbarny** [comment]
Hi,
if you just want to measure the request execution time, you don’t need aspectj at all. Did you have success installing the petclinic example (https://github.com/stagemonitor/stagemonitor/wiki/Installation <https://github.com/stagemonitor/stagemonitor/wiki/Installation>) and did you see the installation guide https://github.com/stagemonitor/stagemonitor/wiki/Installation <https://github.com/stagemonitor/stagemonitor/wiki/Installation>?

**Comment by jhiemer** [comment]
Hi,
thanks for your response. No I did not use Petclinic and started of with my own sample project directly. And yes I read the docs, but it seems that the Http PointCuts are not executed.

**Comment by felixbarny** [comment]
Which servlet api version are you using? You need at least 3.0 for stagemonitor
You can also view the commits of the example integration of stagemonitor into the demo application Spring PetClinic: https://github.com/stagemonitor/spring-petclinic/commits/master <https://github.com/stagemonitor/spring-petclinic/commits/master>

**Comment by jhiemer** [comment]
Taking a look.

**Comment by jhiemer** [comment]
I am running on servlet version 3.0. I also added `-javaagent:"/..../lib/aspectjweaver-1.8.5.jar"` seeing that the startup time of tomcat increased. Debugging into Profiler.java, the breakpoints a catched, but parent is always `null`.

What I don't see as well is `public Object monitorMethodCall(final ProceedingJoinPoint pjp) throws Exception {}` being caught in `RequestMonitorAspect.java`. Is there anything I am doing wrong? Normally the aspect should picked up, without any further configuration, or? :-(

Thanks for your help!

**Comment by felixbarny** [comment]
Forget the aspects for now. The important part for request execution time monitoring is https://github.com/stagemonitor/stagemonitor/blob/584f8fe0b99ec09e3a5f988d01c1f0680b52c3b1/stagemonitor-web/src/main/java/org/stagemonitor/web/monitor/filter/HttpRequestMonitorFilter.java.
Is this filter active (try to set a breakpoint in dofilter)? 
Is your web.xml metadata-complete (https://github.com/stagemonitor/stagemonitor/wiki/Step-1%3A-Prerequisites#servlet-api)?
Are there any stagemonitor entries in your logs?

**Comment by jhiemer** [comment]
@felixbarny thanks for your patience. Now I got it! I am trying to understand your code as fas as possible, because in some points I need to some changes. 

I am currently running an application with Spring MVC and Spring Data Rest and I need to gain some insights. What maybe interesting for you though is, that if I enable `SpringMonitoredHttpRequest.java` with the `@WebListener` configured, stagemonitor throws an 500. The stacktrace is as follows:

```trace
org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping] is defined: expected single matching bean but found 3: repositoryExporterHandlerMapping,requestMappingHandlerMapping,fallbackMapping
  at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:332)
  at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:298)
  at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:968)
  at org.stagemonitor.web.monitor.SpringMonitoredHttpRequest$HandlerMappingServletContextListener.getAllHandlerMappings(SpringMonitoredHttpRequest.java:98)
  at org.stagemonitor.web.monitor.SpringMonitoredHttpRequest$HandlerMappingServletContextListener.requestInitialized(SpringMonitoredHttpRequest.java:107)
  at org.apache.catalina.core.StandardContext.fireRequestInitEvent(StandardContext.java:5926)
  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:131)
  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
  at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)
  at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1085)
  at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
  at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)
  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1556)
  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1513)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
  at java.lang.Thread.run(Thread.java:745)
```

In my opinion the reason is the usage of Spring Data Rest. `repositoryExporterHandlerMapping` is create for automatically exposing JPA/MongoDB Repositories and the `fallbackMapping` is the fallback handler towards MVC controller mappings. I am not sure about the implementation details, but as `repositoryExporterHandlerMapping` is the first HandlerMapping in the execution chain, it should be enough to get the first bean, if multiple are accessible? 

Thanks again. :-)

**Comment by felixbarny** [comment]
What do you mean by 
> enable SpringMonitoredHttpRequest.java with the @WebListener configured

This class should be picked up automatically by the servlet container.
The error should be fixed by this commit: 63cb2ff

Which changes do you need to do? Is this anything that could be interesting for others as well?

**Comment by jhiemer** [comment]
Thanks for that fix.

I want to tweak around a bit with the metrics, I the result is a common applicability for others as well, I will provide a pull-request!

**Comment by felixbarny** [comment]
awesome, thx

**Comment by felixbarny** [comment]
But still, why doesn't SpringMonitoredHttpRequest.java get picked up by your server automatically? Did you mark your web.xml with `metatata-complete`?

**Comment by jhiemer** [comment]
It gets, but it threw the exception, so I disabled it. :-)
