### ISSUE TITLE
Completely Disable Stage Monitor

### ISSUE THREAD

**Issue by swillson** [stagemonitor/stagemonitor#56]
When doing local development I'm unable to completely disable stagemonitor. Is there some way to do this? My current development configuration in eclipse sets the following command line argument:
```
-Dstagemonitor.property.overrides=stagemonitor-local.properties
```
And within that property file I have the following settings:
```
stagemonitor.instanceName=local
stagemonitor.applicationName=My Server
stagemonitor.active=false
stagemonitor.requestmonitor.collectRequestStats=false
stagemonitor.profiler.logCallStacks=false
stagemonitor.requestmonitor.http.collectHeaders=false
stagemonitor.requestmonitor.http.parseUserAgent=false
stagemonitor.web.rum.enabled=false
stagemonitor.web.widget.enabled=false
stagemonitor.profiler.logCallStacks=false
stagemonitor.reporting.interval.console=0
```
I see the following in the log file:
```
2015-Feb-13 20:15:26  INFO [localhost-startStop-1] StagemonitorCoreConfigurationSourceInitializer:28 - try loading of default property overrides: 'stagemonitor-local.properties'
2015-Feb-13 20:15:26  INFO [localhost-startStop-1] Stagemonitor:36 - stagemonitor is deactivated
```
Upon hitting a method that is marked to with @Timer or the like I get the following error:
```
[application=null] [instance=null] [host=null]
Feb 13, 2015 8:22:23 PM org.apache.catalina.core.StandardContext fireRequestInitEvent
SEVERE: Exception sending request initialized lifecycle event to listener instance of class org.stagemonitor.web.logging.MDCListener
java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:514)
	at org.apache.log4j.MDC.put0(MDC.java:150)
	at org.apache.log4j.MDC.put(MDC.java:85)
	at org.slf4j.impl.Log4jMDCAdapter.put(Log4jMDCAdapter.java:59)
	at org.slf4j.MDC.put(MDC.java:113)
	at org.stagemonitor.web.logging.MDCListener.requestInitialized(MDCListener.java:27)
	at org.apache.catalina.core.StandardContext.fireRequestInitEvent(StandardContext.java:6129)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:166)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
```
Am I going about disabling this wrong? This isn't a server I want to track (my local instance running in tomcat / eclipse).

**Comment by felixbarny** [comment]
Well, this is a bug. Expect a fix soon. 
Btw its not about a @Timer method, but the MDCListener that is trying to set null into slf4j's mapped diagnostic context. 
Thanks for reporting!

**Comment by felixbarny** [comment]
Btw 2: you only have to set `stagemonitor.active=false` do disable stagemonitor.
But why do you want to deactivate stagemonitor during local development?

**Comment by swillson** [comment]
I don't want to explicitly not use it, I don't care that it's reporting but I wasn't able to get it working at all locally. No matter what I set in the config file it shows those null values for app name, instance, and host. You can clearly see app name is in the property file, it's claiming to load it, yet its null? I just wanted to get it disabled rather than removing all the changes I made to integrate it. I was grasping at straws going through and disabling everything.

Any ideas why all three things are null despite setting them in the property file? I don't know if it matters but I have 2 wars deployed on this tomcat. Does that impact the startup and init of Stage Monitor?

**Comment by felixbarny** [comment]
Well, if you disable stagemonitor (`stagemonitor.active=false`) the MeasurementSession doesn't get initialized so the application name is null.
