### ISSUE TITLE
Exception when registering MonitorRequestsInstrumenter on Java 6

### ISSUE THREAD

**Issue by alecxvs** [stagemonitor/stagemonitor#75]
An exception is thrown related to the Java version when Stagemonitor tries to load MonitorRequestsInstrumenter. It seems to be related to elastic search, but doesn't break any current functionality.

Log:
```
May 15, 2015 2:19:02 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-bio-8080"]
May 15, 2015 2:19:02 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Tomcat
May 15, 2015 2:19:02 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.47
May 15, 2015 2:19:19 PM org.apache.tomcat.websocket.server.WsSci onStartup
INFO: JSR 356 WebSocket (Java WebSocket 1.0) support is not available when running on Java 6. To suppress this message, run Tomcat on Java 7, remove the WebSocket JARs from $CATALINA_HOME/lib or add the WebSocketJARs to the tomcat.util.scan.DefaultJarScanner.jarsToSkip property in $CATALINA_BASE/conf/catalina.properties. Note that the deprecated Tomcat 7 WebSocket API will be available. 
May 15, 2015 2:19:19 PM org.stagemonitor.core.instrument.AgentLoader warnIfOSX
WARNING: Loading the SizeOfAgent will probably fail, as you are running on Apple OS X and have a value set for java.io.tmpdir
They both result in a bug, not yet fixed by Apple, that won't let us attach to the VM and load the agent.
Most probably, you'll also get a full thread-dump after this because of the failure... Nothing to worry about!
You can load the agent with the command line argument -javaagent:/path/to/stagemonitor-javaagent-<version>.jar
May 15, 2015 2:19:19 PM org.stagemonitor.core.instrument.AgentLoader loadAgent
INFO: Trying to load agent @ /Users/as032696/.m2/repository/org/stagemonitor/stagemonitor-javaagent/0.14.0/stagemonitor-javaagent-0.14.0.jar
15/05/15 14:19:19 [correlation_id=] INFO instrument.MainStagemonitorClassFileTransformer: Registering ExceptionMeteredInstrumenter
15/05/15 14:19:19 [correlation_id=] INFO instrument.MainStagemonitorClassFileTransformer: Registering MeteredInstrumenter
15/05/15 14:19:19 [correlation_id=] INFO instrument.MainStagemonitorClassFileTransformer: Registering TimedInstrumenter
15/05/15 14:19:19 [correlation_id=] INFO instrument.MainStagemonitorClassFileTransformer: Registering GaugeInstrumenter
15/05/15 14:19:19 [correlation_id=] INFO instrument.MainStagemonitorClassFileTransformer: Registering ProfilingInstrumenter
15/05/15 14:19:19 [correlation_id=] INFO instrument.MainStagemonitorClassFileTransformer: Registering MonitorRequestsInstrumenter
java.util.ServiceConfigurationError: org.stagemonitor.core.instrument.StagemonitorJavassistInstrumenter: Provider org.stagemonitor.requestmonitor.profiler.elasticsearch.ElasticsearchSearchQueryInstrumenter could not be instantiated: java.lang.UnsupportedClassVersionError: org/elasticsearch/action/search/SearchRequestBuilder : Unsupported major.minor version 51.0
	at java.util.ServiceLoader.fail(ServiceLoader.java:207)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:164)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:360)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:428)
	at org.stagemonitor.core.instrument.MainStagemonitorClassFileTransformer.<init>(MainStagemonitorClassFileTransformer.java:36)
	at org.stagemonitor.core.instrument.MainStagemonitorClassFileTransformer.performRuntimeAttachment(MainStagemonitorClassFileTransformer.java:60)
	at org.stagemonitor.web.attach.RuntimeAgentAttacherListener.<clinit>(RuntimeAgentAttacherListener.java:25)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at java.lang.Class.newInstance0(Class.java:357)
	at java.lang.Class.newInstance(Class.java:310)
	at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:143)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4854)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5434)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
Caused by: java.lang.UnsupportedClassVersionError: org/elasticsearch/action/search/SearchRequestBuilder : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at org.apache.catalina.loader.WebappClassLoader.findClass(WebappClassLoader.java:1191)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1669)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1547)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:171)
	at org.stagemonitor.core.util.ClassUtils.forNameOrNull(ClassUtils.java:7)
	at org.stagemonitor.core.util.ClassUtils.isPresent(ClassUtils.java:14)
	at org.stagemonitor.requestmonitor.profiler.elasticsearch.ElasticsearchSearchQueryInstrumenter.<init>(ElasticsearchSearchQueryInstrumenter.java:18)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at java.lang.Class.newInstance0(Class.java:357)
	at java.lang.Class.newInstance(Class.java:310)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:356)
	... 21 more
```

**Comment by felixbarny** [comment]
Elasticsearch is not Java 6 compliant but I'm wondering why Elasticsearch seems to be on your classpath. Elasticsearch is declared as a optional dependency in pom.xml.
Which dependency management system are you using? Could you confirm that the es jar is on your classpath?

**Comment by felixbarny** [comment]
The issue was that I screwed up on declaring the dependency as optional. I'm just releasing a new version 0.14.1.
