### ISSUE TITLE
Stagemonitor crash on start in Tomcat 8

### ISSUE THREAD

**Issue by johanstenberg92** [stagemonitor/stagemonitor#83]
Hi,

I just got this:

```
Failed to perform runtime attachment of the stagemonitor agent. You can load the agent with the command line argument -javaagent:/path/to/stagemonitor-javaagent-<version>.jar
```

```
java.lang.NullPointerException: null
	at org.stagemonitor.core.instrument.MainStagemonitorClassFileTransformer.performRuntimeAttachment(MainStagemonitorClassFileTransformer.java:64) ~[stagemonitor-core-0.15.2.jar:0.15.2]
	at org.stagemonitor.core.Stagemonitor.reset(Stagemonitor.java:194) [stagemonitor-core-0.15.2.jar:0.15.2]
	at org.stagemonitor.core.Stagemonitor.<clinit>(Stagemonitor.java:35) [stagemonitor-core-0.15.2.jar:0.15.2]
	at org.stagemonitor.web.WebPlugin.<clinit>(WebPlugin.java:56) [stagemonitor-web-0.15.2.jar:0.15.2]
	at java.lang.Class.forName0(Native Method) [na:1.8.0_45]
	at java.lang.Class.forName(Class.java:348) [na:1.8.0_45]
	at org.apache.catalina.startup.WebappServiceLoader.loadServices(WebappServiceLoader.java:181) [catalina.jar:8.0.20]
	at org.apache.catalina.startup.WebappServiceLoader.load(WebappServiceLoader.java:151) [catalina.jar:8.0.20]
	at org.apache.catalina.startup.ContextConfig.processServletContainerInitializers(ContextConfig.java:1617) [catalina.jar:8.0.20]
	at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1128) [catalina.jar:8.0.20]
	at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:771) [catalina.jar:8.0.20]
	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:305) [catalina.jar:8.0.20]
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117) [catalina.jar:8.0.20]
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90) [catalina.jar:8.0.20]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5061) [catalina.jar:8.0.20]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:8.0.20]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) [catalina.jar:8.0.20]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) [catalina.jar:8.0.20]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717) [catalina.jar:8.0.20]
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1069) [catalina.jar:8.0.20]
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1719) [catalina.jar:8.0.20]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_45]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```

My config is:

```
stagemonitor.instrument.include=shortcut.flic
stagemonitor.applicationName=Flic Test Website
stagemonitor.elasticsearch.url=http://monitor.flic.io:8888/elasticsearch
stagemonitor.reporting.graphite.hostName=monitor.flic.io
stagemonitor.web.widget.enabled=false
```

I also get these when trying to visit the site:

```
[http-nio-8080-exec-1] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [shortcut.flic.website.FlicWebsiteController] in context with path [] threw exception
 java.io.CharConversionException: Not an ISO 8859-1 character: â€™
	at javax.servlet.ServletOutputStream.print(ServletOutputStream.java:75)
	at org.stagemonitor.web.monitor.filter.HttpRequestMonitorFilter.injectHtmlToOutputStream(HttpRequestMonitorFilter.java:202)
	at org.stagemonitor.web.monitor.filter.HttpRequestMonitorFilter.injectHtml(HttpRequestMonitorFilter.java:183)
	at org.stagemonitor.web.monitor.filter.HttpRequestMonitorFilter.doMonitor(HttpRequestMonitorFilter.java:130)
	at org.stagemonitor.web.monitor.filter.HttpRequestMonitorFilter.doFilterInternal(HttpRequestMonitorFilter.java:102)
	at org.stagemonitor.web.monitor.filter.AbstractExclusionFilter.doFilter(AbstractExclusionFilter.java:75)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:673)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by felixbarny** [comment]
Any exceptions before the NPE? Which JDK are you using?

**Comment by johanstenberg92** [comment]
Hi,

I'm using:

```
openjdk version "1.8.0_45"
OpenJDK Runtime Environment (build 1.8.0_45-b13)
OpenJDK 64-Bit Server VM (build 25.45-b02, mixed mode)
```

```
05:54:05.070 [localhost-startStop-1] INFO  o.s.c.StagemonitorCoreConfigurationSourceInitializer - try loading of default property overrides: 'stagemonitor-test.properties'
02-Jul-2015 05:54:05.141 INFO [localhost-startStop-1] null.null Unavailable or unrecognised attach API : java.lang.ClassNotFoundException: com.sun.tools.attach.VirtualMachine
05:54:05.193 [localhost-startStop-1] INFO  o.s.c.i.MainStagemonitorClassFileTransformer - Registering ConnectionMonitoringInstrumenter
05:54:05.194 [localhost-startStop-1] INFO  o.s.c.i.MainStagemonitorClassFileTransformer - Registering ExceptionMeteredInstrumenter
05:54:05.200 [localhost-startStop-1] INFO  o.s.c.i.MainStagemonitorClassFileTransformer - Registering MeteredInstrumenter
05:54:05.203 [localhost-startStop-1] INFO  o.s.c.i.MainStagemonitorClassFileTransformer - Registering TimedInstrumenter
05:54:05.203 [localhost-startStop-1] INFO  o.s.c.i.MainStagemonitorClassFileTransformer - Registering GaugeInstrumenter
05:54:05.204 [localhost-startStop-1] INFO  o.s.c.i.MainStagemonitorClassFileTransformer - Registering SpringMvcRequestNameDeterminerInstrumenter
05:54:05.209 [localhost-startStop-1] INFO  o.s.c.i.MainStagemonitorClassFileTransformer - Registering ProfilingInstrumenter
05:54:05.218 [localhost-startStop-1] INFO  o.s.c.i.MainStagemonitorClassFileTransformer - Registering MonitorRequestsInstrumenter
05:54:05.219 [localhost-startStop-1] INFO  o.s.c.i.MainStagemonitorClassFileTransformer - Registering ElasticsearchSearchQueryInstrumenter
05:54:05.226 [localhost-startStop-1] WARN  o.s.c.i.MainStagemonitorClassFileTransformer - Failed to perform runtime attachment of the stagemonitor agent. You can load the agent with the command line argument -javaagent:/path/to/stagemonitor-javaagent-<version>.jar
java.lang.NullPointerException: null
	at org.stagemonitor.core.instrument.MainStagemonitorClassFileTransformer.performRuntimeAttachment(MainStagemonitorClassFileTransformer.java:64) ~[stagemonitor-core-0.15.2.jar:0.15.2]
	at org.stagemonitor.core.Stagemonitor.reset(Stagemonitor.java:194) [stagemonitor-core-0.15.2.jar:0.15.2]
	at org.stagemonitor.core.Stagemonitor.<clinit>(Stagemonitor.java:35) [stagemonitor-core-0.15.2.jar:0.15.2]
	at org.stagemonitor.web.WebPlugin.<clinit>(WebPlugin.java:56) [stagemonitor-web-0.15.2.jar:0.15.2]
	at java.lang.Class.forName0(Native Method) [na:1.8.0_45]
	at java.lang.Class.forName(Class.java:348) [na:1.8.0_45]
	at org.apache.catalina.startup.WebappServiceLoader.loadServices(WebappServiceLoader.java:181) [catalina.jar:8.0.20]
	at org.apache.catalina.startup.WebappServiceLoader.load(WebappServiceLoader.java:151) [catalina.jar:8.0.20]
	at org.apache.catalina.startup.ContextConfig.processServletContainerInitializers(ContextConfig.java:1617) [catalina.jar:8.0.20]
	at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1128) [catalina.jar:8.0.20]
	at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:771) [catalina.jar:8.0.20]
	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:305) [catalina.jar:8.0.20]
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117) [catalina.jar:8.0.20]
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90) [catalina.jar:8.0.20]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5061) [catalina.jar:8.0.20]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:8.0.20]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) [catalina.jar:8.0.20]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) [catalina.jar:8.0.20]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717) [catalina.jar:8.0.20]
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1069) [catalina.jar:8.0.20]
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1719) [catalina.jar:8.0.20]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_45]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
02-Jul-2015 05:54:13.242 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
05:54:13.253 [localhost-startStop-1] INFO  o.s.w.c.ConfigurationServlet - Registering configuration Endpoint /stagemonitor/configuration. You can dynamically change the configuration by issuing a POST request to /stagemonitor/configuration?key=stagemonitor.config.key&value=configValue&stagemonitor.password=password. If the password is not set, dynamically changing the configuration is not available. The password can be omitted if set to an empty string.
05:54:13.405 [localhost-startStop-1] INFO  o.scalatra.servlet.ScalatraListener - The cycle class name from the config: ScalatraBootstrap
05:54:13.695 [localhost-startStop-1] INFO  o.scalatra.servlet.ScalatraListener - Initializing life cycle class: ScalatraBootstrap
05:54:15.202 [localhost-startStop-1] INFO  com.zaxxer.hikari.HikariDataSource - HikariCP pool HikariPool-0 is starting.
05:54:17.114 [localhost-startStop-1] INFO  o.f.s.servlet.ServletTemplateEngine - Scalate template engine using working directory: /var/cache/tomcat8/temp/scalate-7751986278466722844-workdir
02-Jul-2015 05:54:17.151 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /var/lib/tomcat8/webapps/ROOT has finished in 13,879 ms
02-Jul-2015 05:54:17.158 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
02-Jul-2015 05:54:17.172 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
02-Jul-2015 05:54:17.176 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 13972 ms
05:54:35.414 [pool-5-thread-1] INFO  org.stagemonitor.core.Stagemonitor - Initializing plugin OsPlugin
05:54:36.184 [pool-5-thread-1] INFO  org.stagemonitor.core.Stagemonitor - Initializing plugin JdbcPlugin
05:54:36.200 [pool-5-thread-1] INFO  org.stagemonitor.core.Stagemonitor - Initializing plugin CorePlugin
05:54:36.268 [pool-5-thread-1] INFO  org.stagemonitor.core.Stagemonitor - Initializing plugin JvmPlugin
05:54:36.351 [pool-5-thread-1] INFO  org.stagemonitor.core.Stagemonitor - Initializing plugin AlertingPlugin
05:54:36.548 [pool-5-thread-1] INFO  o.s.alerting.AlertingPlugin - Using ElasticsearchIncidentRepository for storing incidents.
05:54:36.556 [pool-5-thread-1] INFO  org.stagemonitor.core.Stagemonitor - Initializing plugin WebPlugin
05:54:36.569 [pool-5-thread-1] INFO  org.stagemonitor.core.Stagemonitor - Initializing plugin RequestMonitorPlugin
05:54:36.589 [pool-5-thread-1] INFO  org.stagemonitor.core.Stagemonitor - Measurement Session is initialized: [application=Flic Test Website] [instance=sandbox.flic.io] [host=ip-172-31-10-203]
05:57:43.480 [metrics-graphite-reporter-1-thread-1] WARN  c.c.m.graphite.GraphiteReporter - Unable to report to Graphite
java.net.ConnectException: Connection timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_45]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345) ~[na:1.8.0_45]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_45]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_45]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_45]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_45]
	at java.net.Socket.connect(Socket.java:538) ~[na:1.8.0_45]
	at java.net.Socket.<init>(Socket.java:434) ~[na:1.8.0_45]
	at java.net.Socket.<init>(Socket.java:244) ~[na:1.8.0_45]
	at javax.net.DefaultSocketFactory.createSocket(SocketFactory.java:277) ~[na:1.8.0_45]
	at com.codahale.metrics.graphite.Graphite.connect(Graphite.java:118) ~[metrics-graphite-3.1.2.jar:3.1.2]
	at com.codahale.metrics.graphite.GraphiteReporter.report(GraphiteReporter.java:167) ~[metrics-graphite-3.1.2.jar:3.1.2]
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:162) [metrics-core-3.1.2.jar:3.1.2]
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:117) [metrics-core-3.1.2.jar:3.1.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_45]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_45]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_45]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```

**Comment by felixbarny** [comment]
Do you have a basic application that reproduces the error?

**Comment by felixbarny** [comment]
Did you try to start the application with `-javaagent:/path/to/stagemonitor-javaagent-<version>.jar` as suggested in the exception message?
